In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [115]:
EPS = 1e-12

def moore_penrose_2x2(A):
    At = np.zeros((2,2),dtype=np.float32)
    
    a = A[0,0]
    b = A[0,1]
    c = A[1,0]
    d = A[1,1]
    
    a2 = a*a
    b2 = b*b
    c2 = c*c
    d2 = d*d
    
    a2b2 = a2+b2
    c2d2 = c2+d2
    a2b2nc2nd2 = a2b2-c2d2
    tacbd = 2*(a*c+b*d)
    
    theta = 0.5*np.arctan2(2*(a*b+c*d),a2+c2-b2-d2)
    phi = 0.5*np.arctan2(tacbd, a2b2nc2nd2)
    
    ctheta = np.cos(theta)
    cphi = np.cos(phi)
    stheta = np.sin(theta)
    sphi = np.sin(phi)
    
    ctcp = ctheta*cphi
    ctsp = ctheta*sphi
    stcp = stheta*cphi
    stsp = stheta*sphi
    
    sign0 = np.sign(ctcp*a+ctsp*c+stcp*b+stsp*d)
    sign1 = np.sign(stsp*a-stcp*c-ctsp*b+ctcp*d)
    
    ss = a2b2+c2d2
    sd = np.sqrt(a2b2nc2nd2**2+tacbd**2)
    
    sig0 = np.sqrt((ss+sd)/2.0)
    sig1 = np.sqrt((ss-sd)/2.0)
    
    thresh = EPS*2*sig0
    
    siginv0 = (1.0/sig0) if (sig0 > thresh) else 0.0
    siginv1 = (1.0/sig1) if (sig1 > thresh) else 0.0
    
    s0s0 = sign0*siginv0
    s1s1 = sign1*siginv1
    
    At[0,0] = ctcp*s0s0+stsp*s1s1
    At[0,1] = ctsp*s0s0-stcp*s1s1
    At[1,0] = stcp*s0s0-ctsp*s1s1
    At[1,1] = stsp*s0s0+ctcp*s1s1
    
    return At

In [126]:
a = np.random.rand(2,2)
a

array([[0.83700616, 0.60502218],
       [0.48288836, 0.32125766]])

In [127]:
np.linalg.pinv(a)

array([[-13.80950021,  26.00732972],
       [ 20.75731634, -35.97933427]])

In [128]:
moore_penrose_2x2(a)

array([[-13.8095  ,  26.00733 ],
       [ 20.757317, -35.979336]], dtype=float32)

In [125]:
for i in np.arange(1000):
    a = np.random.rand(2,2)
    np.testing.assert_almost_equal(np.linalg.pinv(a),moore_penrose_2x2(a),decimal=3)