In [1]:
%gui wx

from PYME.LMVis import VisGUI

/Users/zachcm/opt/miniconda3/envs/pyme/lib/python3.7/_collections_abc.py:702: MatplotlibDeprecationWarning: The global colormaps dictionary is no longer considered public API.
  return len(self._mapping)
/Users/zachcm/opt/miniconda3/envs/pyme/lib/python3.7/_collections_abc.py:720: MatplotlibDeprecationWarning: The global colormaps dictionary is no longer considered public API.
  yield from self._mapping
/Users/zachcm/Code/python-microscopy/PYME/misc/extraCMaps.py:73: MatplotlibDeprecationWarning: 
The revcmap function was deprecated in Matplotlib 3.2 and will be removed two minor releases later. Use Colormap.reversed() instead.
  cmapdat_r = cm.revcmap(ndat[cmapname])
INFO:OpenGL.acceleratesupport:No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'


Trying to load 3rd party recipe module ch_shrinkwrap.recipe_modules.surface_fitting
Loaded 3rd party recipe module ch_shrinkwrap.recipe_modules.surface_fitting
quaternion module not found, disabling custom clip plane orientations
quaternion module not found, disabling custom clip plane orientations


In [2]:
# Delay so wx can boot up
import time
time.sleep(8)

In [3]:
pymevis = VisGUI.ipython_pymevisualize()
pipeline = pymevis.pipeline
recipe = pipeline.recipe

DEBUG:PYME.LMVis.visCore:Creating VisGUI menu bar
DEBUG:PYME.LMVis.Extras:Initializing QPobjectSegment plugin
DEBUG:PYME.LMVis.Extras:Initializing animation plugin
DEBUG:PYME.LMVis.Extras:Initializing clusterAnalysis plugin
DEBUG:PYME.LMVis.Extras:Initializing dockedPanel plugin
DEBUG:PYME.LMVis.Extras:Initializing extra_layers plugin
DEBUG:PYME.LMVis.Extras:Initializing fiducial plugin
DEBUG:PYME.LMVis.Extras:Initializing flagZMotionArtifacts plugin
DEBUG:root:Adding menu items for event filters
DEBUG:PYME.LMVis.Extras:Initializing fusionUtils plugin
DEBUG:PYME.LMVis.Extras:Initializing multiColourAnalysis plugin
DEBUG:PYME.LMVis.Extras:Initializing multiviewMapping plugin
DEBUG:root:Adding menu items for multi-view manipulation
DEBUG:PYME.LMVis.Extras:Initializing objectMeasurements plugin
DEBUG:PYME.LMVis.Extras:Initializing particleTracking plugin
DEBUG:PYME.LMVis.Extras:Initializing perFrameVariable plugin
DEBUG:PYME.LMVis.Extras:Initializing photophysics plugin
DEBUG:PYME.LMVis.E

New Canvas
Saved Views are deprecated -  use the ones with animation instead and remove me!


/Users/zachcm/Code/python-microscopy/PYME/LMVis/filterPane.py:111: wxPyDeprecationWarning: Call to deprecated item. Use InsertItem instead.
  ind = self.lFiltKeys.InsertStringItem(ind+1, key)
/Users/zachcm/Code/python-microscopy/PYME/LMVis/filterPane.py:112: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 1, '%3.2f' % value[0])
/Users/zachcm/Code/python-microscopy/PYME/LMVis/filterPane.py:113: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 2, '%3.2f' % value[1])


Creating fold panel
GenPanels
Creating datasource panel
RecipeView._layout
Input datasources:  []
Image list size: 1
Creating layers GUI
height:  0
NB best size: wx.Size(200, 0)
RecipeView._layout
Input datasources:  []
RecipeView._layout
Input datasources:  []
0


/Users/zachcm/Code/python-microscopy/PYME/LMVis/filterPane.py:111: wxPyDeprecationWarning: Call to deprecated item. Use InsertItem instead.
  ind = self.lFiltKeys.InsertStringItem(ind+1, key)
/Users/zachcm/Code/python-microscopy/PYME/LMVis/filterPane.py:112: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 1, '%3.2f' % value[0])
/Users/zachcm/Code/python-microscopy/PYME/LMVis/filterPane.py:113: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 2, '%3.2f' % value[1])
DEBUG:PYME.LMVis.shader_programs.ShaderProgramFactory:New shader program created: <class 'PYME.LMVis.shader_programs.DefaultShaderProgram.DefaultShaderProgram'>


OpenGL - Version: b'2.1 INTEL-14.7.8'
Shader - Version: b'1.20'
GL_MAX_SAMPLES: 8, GL_SAMPLES: 4


/Users/zachcm/Code/python-microscopy/PYME/ui/manualFoldPanel.py:37: wxPyDeprecationWarning: Using deprecated class. Use Colour instead.
  col = wx.NamedColour(col)


In [4]:
from ch_shrinkwrap import shape
from PYME.IO import tabular
import numpy as np

# Create a torus
R = 50
r = 30
# t = shape.Torus(R, r)
# pts_t = t.points(1)
pts_t = np.load('hemo_pts.npy')

# Create a bounding box
# import numpy as np
# pts_t = np.vstack([pts_t, np.array([-2*R,-2*R,-2*R]), np.array([2*R,2*R,2*R])])

pipeline.addDataSource('points', tabular.mappingFilter({'x' : pts_t[:,0], 'y':pts_t[:,1], 'z':pts_t[:,2]}))
pipeline.selectDataSource('points')
pymevis.add_pointcloud_layer(ds_name='points')

/Users/zachcm/Code/python-microscopy/PYME/IO/tabular.py:48: VisibleDeprecationWarning: mappingFilter is deprecated, use MappingFilter instead
  warnings.warn(VisibleDeprecationWarning('%s is deprecated, use %s instead' % (name, cls.__name__)))
/Users/zachcm/Code/python-microscopy/PYME/IO/tabular.py:928: VisibleDeprecationWarning: Mapping filter created with something that is not a tabular object. This will be unsupported in a future release. Consider DictSource or ColumnSource instead
  warnings.warn(VisibleDeprecationWarning('Mapping filter created with something that is not a tabular object. This will be unsupported in a future release. Consider DictSource or ColumnSource instead'))
DEBUG:PYME.LMVis.shader_programs.ShaderProgramFactory:New shader program created: <class 'PYME.LMVis.shader_programs.DefaultShaderProgram.OpaquePointShaderProgram'>


lw update
lw update
Creating layers GUI


/Users/zachcm/Code/python-microscopy/PYME/LMVis/layers/base.py:65: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  self.shader_program.v_matrix[3,:3] = -np.linalg.lstsq(gl_canvas.object_rotation_matrix[:3,:3], gl_canvas.view.translation)[0]
DEBUG:PYME.LMVis.visCore:Added layer, datasouce=points


hl update
height:  308
NB best size: wx.Size(243, 308)


In [5]:
# Surface generation parameters
threshold_density = 0.005
# threshold_density = 0.0001
n_points_min = 50
# n_points_min = 100
repair = False
remesh = False

# Run surface generation recipe on the point cloud
from PYME.LMVis.Extras import extra_layers
from PYME.LMVis.layers.mesh import TriangleRenderLayer
from PYME.recipes.surface_fitting import DualMarchingCubes
from ch_shrinkwrap import _membrane_mesh as membrane_mesh

# oc_name = extra_layers.gen_octree_from_points(pymevis)
surf_name, surf_count = pipeline.new_ds_name('surf', return_count=True)
# dmc = DualMarchingCubes(recipe, invalidate_parent=False, input=oc_name, output=surf_name, threshold_density=threshold_density, n_points_min=n_points_min, repair=repair, remesh=remesh)
# recipe.add_module(dmc)
# recipe.execute()
# layer = TriangleRenderLayer(pipeline, dsname=surf_name, method='shaded', cmap = ['C', 'M', 'Y', 'R', 'G', 'B'][surf_count % 6])
# pymevis.add_layer(layer)
# dmc._invalidate_parent = True
mesh = membrane_mesh.MembraneMesh.from_stl('hemo.stl')
pipeline.dataSources[surf_name] = mesh
layer = TriangleRenderLayer(pipeline, dsname=surf_name, method='shaded', cmap = ['C', 'M', 'Y', 'R', 'G', 'B'][surf_count % 6])
pymevis.add_layer(layer)

DEBUG:PYME.LMVis.shader_programs.ShaderProgramFactory:New shader program created: <class 'PYME.LMVis.shader_programs.GouraudShaderProgram.GouraudShaderProgram'>


Data munged to vertices, faces
initializing halfedges ...
vertices.shape = (529, 3), faces.shape = (1054, 3)
iterating edges
done initializing halfedges
lw update
Disposing of HistLimitsEditor
Creating layers GUI
hl update
hl update
height:  335
NB best size: wx.Size(200, 335)


/Users/zachcm/Code/python-microscopy/PYME/ui/layerFoldPanel.py:47: wxPyDeprecationWarning: Call to deprecated item BitmapFromBuffer. Use :meth:`wx.Bitmap.FromBuffer` or :meth:`wx.Bitmap.FromBufferAndAlpha` instead.
  return wx.BitmapFromBuffer(30, 10, img)
/Users/zachcm/Code/python-microscopy/PYME/ui/histLimits.py:289: wxPyDeprecationWarning: Call to deprecated item EmptyBitmap. Use :class:`wx.Bitmap` instead
  MemBitmap = wx.EmptyBitmap(s.GetWidth(), s.GetHeight())


In [6]:
# Shrinkwrapping parameters
max_iters = 1
step_size = 0.1
attraction_weight = 1  # eV/nm
curvature_weight = 1
largest_component_only = True
method = 'euler'
remesh_every = 500  # iterations
remesh_frequency = 0
delaunay_remesh_frequency = 0

In [7]:
from PYME.util import mProfile
import time

# mProfile.profileOn(['_membrane_mesh.pyx'])

# Run surface meshing on the point cloud
membrane_name = pipeline.new_ds_name('membrane')

points_name = 'points'

mesh = membrane_mesh.MembraneMesh(mesh=recipe.namespace[surf_name])
mesh.a = attraction_weight
mesh.c = curvature_weight
mesh.max_iter = 6
mesh.step_size = step_size
mesh.remesh_frequency = remesh_frequency
mesh.delaunay_remesh_frequency = delaunay_remesh_frequency
# mesh.keep_largest_connected_component()
# mesh.kg = 0

pts = np.ascontiguousarray(np.vstack([recipe.namespace[points_name]['x'], 
                                      recipe.namespace[points_name]['y'],
                                      recipe.namespace[points_name]['z']]).T)

try:
    sigma = recipe.namespace[points_name]['sigma']
except(KeyError):
    sigma = np.ones_like(recipe.namespace[points_name]['x'])
    
residuals = []
res_prev = 1e10
mesh_prev = membrane_mesh.MembraneMesh(mesh=mesh)
start = time.time()
for _i in range(max_iters):
    print('Iteration {} <<<'.format(_i))
    mesh.shrink_wrap(pts, sigma, method=method)
    if ((_i+1) % remesh_every) == 0:
        mesh.remesh()
#     comparison_points = mesh._vertices['position'][mesh._vertices['halfedge']!=-1]
#     new_res = s.surface_res(comparison_points)
#     residuals.append(new_res)
stop = time.time()
print('Time elapsed = {} s'.format(stop-start))
# mProfile.profileOff()
# mProfile.report()

Iteration 0 <<<
Iteration 0 ...
((3, 3), (6, 3))
(array([[ 0.02505749,  0.12222194, -0.09742415],
       [ 0.12222194,  0.98467786,  0.01221341],
       [-0.09742415,  0.01221341,  0.99026459]]), array([[  0.2993393 ,   2.5652542 ,  11.128048  ],
       [  3.321083  ,   9.913801  ,   5.5698614 ],
       [  4.2859726 ,   9.334961  ,  -8.56844   ],
       [  1.5804443 ,  -1.8268723 , -10.960474  ],
       [  2.3833847 , -10.620859  ,  -3.2391427 ],
       [  0.09584808,  -7.5688214 ,   7.2764854 ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.04099751, -0.19820957, -0.00545178],
       [-0.19820957,  0.95903344, -0.00112679],
       [-0.00545178, -0.00112679,  0.99996901]]), array([[  2.8738098 ,  -7.377141  ,   9.184574  ],
       [  0.8188782 ,   3.612633  ,  10.878611  ],
       [  0.20349121,  10.134075  ,   3.851563  ],
       [ -0.09584808,   7.5688214 ,  -7.2764854 ],
       [  2.2875366 ,  -3.0520372 , -10.515628  ],
       [  4.3414307 ,  -9.817673  ,  -3.6256967 ]], dtype=floa

((3, 3), (5, 3))
(array([[ 0.94871603,  0.21996811, -0.01636951],
       [ 0.21996811,  0.0565089 ,  0.07021238],
       [-0.01636951,  0.07021238,  0.99477496]]), array([[-11.403019  ,  -4.4308186 ,  -0.726841  ],
       [ -1.8316956 ,   0.11818504,  10.887678  ],
       [  8.553013  ,   0.78043556,   3.6699953 ],
       [  7.2499504 ,   0.31378365,  -5.663719  ],
       [ -1.5842514 ,  -1.4143085 ,  -7.785574  ]], dtype=float32))
((3, 3), (7, 3))
(array([[ 0.91182373, -0.28073207,  0.03988377],
       [-0.28073207,  0.10621649,  0.12698035],
       [ 0.03988377,  0.12698035,  0.98195983]]), array([[ -5.7615204 ,   4.3098354 ,   7.8028297 ],
       [ -8.850658  ,   3.9200115 ,  -0.85015297],
       [ -5.823803  ,  -0.05838966,  -9.508326  ],
       [  3.1563911 ,  -1.6414146 , -10.031563  ],
       [  9.377365  ,  -2.212717  ,  -5.060404  ],
       [  7.7256355 ,  -1.2432404 ,   5.3679466 ],
       [  0.67422485,   0.72420883,   9.209888  ]], dtype=float32))
((3, 3), (5, 3))
(array([[

((3, 3), (5, 3))
(array([[ 0.76882485, -0.19426234, -0.37415951],
       [-0.19426234,  0.83675644, -0.31441572],
       [-0.37415951, -0.31441572,  0.39441872]]), array([[ 6.114628  ,  4.3694725 , -4.898613  ],
       [ 9.671377  , -4.571948  , -0.25117493],
       [ 3.2791405 , -7.872485  ,  5.1523895 ],
       [-6.6808662 , -0.7142353 ,  5.8624687 ],
       [-4.985817  ,  9.05105   ,  2.6399612 ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.98990116, -0.09988009, -0.00456251],
       [-0.09988009,  0.01216006, -0.04512436],
       [-0.00456251, -0.04512436,  0.99793873]]), array([[ 10.995611  ,  -1.3345623 ,  -3.4309196 ],
       [  6.3622437 ,   0.04148102,   9.700935  ],
       [ -3.672638  ,  -0.47743988,   8.180132  ],
       [-10.636612  ,   1.6466541 ,   1.1943665 ],
       [ -6.5851173 ,   1.1751194 ,  -5.9011955 ],
       [  3.7621078 ,   0.4673233 ,  -8.813427  ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.97905838,  0.14318393, -0.00119438],
       [ 0.14318393,  0.02

((3, 3), (6, 3))
(array([[ 0.98276702, -0.12913363, -0.01614034],
       [-0.12913363,  0.03234994, -0.12094605],
       [-0.01614034, -0.12094605,  0.98488302]]), array([[-6.579674  ,  2.424553  , -5.765148  ],
       [-9.6132965 ,  1.5274124 ,  3.0182915 ],
       [-0.8491459 , -0.60611725,  9.794686  ],
       [ 7.49519   , -0.91090775,  5.6779804 ],
       [ 6.67598   ,  0.09256744, -2.8625202 ],
       [ 0.16799164,  1.2521687 , -6.848366  ]], dtype=float32))
((3, 3), (5, 3))
(array([[ 0.98294233, -0.12656417, -0.0273535 ],
       [-0.12656417,  0.06092155, -0.20295699],
       [-0.0273535 , -0.20295699,  0.95613621]]), array([[-6.7476654 ,  1.1723843 ,  1.0832176 ],
       [-0.16799164, -1.2521687 ,  6.848366  ],
       [ 6.5079885 , -1.1596012 ,  3.9858456 ],
       [ 5.677847  ,  0.6625042 , -5.4065895 ],
       [-3.8907356 ,  2.2024937 , -5.8058205 ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.99984174,  0.01238607, -0.00219454],
       [ 0.01238607,  0.03059018,  0.1717584

       [-12.803339  ,  -0.68748283,   0.8918308 ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.99962252,  0.01531221, -0.01195277],
       [ 0.01531221,  0.3788628 ,  0.48486212],
       [-0.01195277,  0.48486212,  0.62151477]]), array([[11.222615 ,  2.1683445,  2.384201 ],
       [ 3.3383946,  7.886466 ,  7.166252 ],
       [-7.4200907,  6.057083 ,  5.803734 ],
       [-8.41316  , -1.1075802, -1.4187088],
       [-5.1389027, -5.2208176, -8.869545 ],
       [ 9.620387 , -3.2260532, -6.630562 ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.99422837,  0.07564884,  0.00394641],
       [ 0.07564884,  0.00847018, -0.05172556],
       [ 0.00394641, -0.05172556,  0.99730161]]), array([[  6.1522703 ,  -0.3757763 ,   8.331724  ],
       [ -4.1427383 ,  -1.6281719 ,   8.736368  ],
       [-11.839486  ,  -1.551096  ,   0.9346714 ],
       [ -6.837042  ,  -0.64910126,  -7.740939  ],
       [  4.789944  ,   0.06345177,  -8.788814  ],
       [ 10.635271  ,   0.13760948,  -0.6660166 ]], dtype=floa

((3, 3), (6, 3))
(array([[ 0.99669678, -0.05714249, -0.00520093],
       [-0.05714249,  0.01149207, -0.0899708 ],
       [-0.00520093, -0.0899708 ,  0.99181115]]), array([[ -7.040352  ,   2.2637234 ,  -8.36459   ],
       [  4.5134068 ,   0.76264954,  -9.425522  ],
       [ 11.272276  ,  -0.69664955,  -1.5264454 ],
       [  5.456726  ,   0.06230545,  11.252544  ],
       [ -4.7801247 ,  -0.55724716,   7.6809998 ],
       [-11.423174  ,   0.6357231 ,   0.6764946 ]], dtype=float32))
((3, 3), (5, 3))
(array([[ 0.98629116, -0.09749828,  0.063364  ],
       [-0.09749828,  0.30658525,  0.45064932],
       [ 0.063364  ,  0.45064932,  0.70712361]]), array([[-1.034195 , -6.4308853, -7.4569664],
       [-8.413435 , -1.3111477, -2.0682106],
       [-5.883292 ,  3.2467785,  7.477379 ],
       [ 5.6071014,  2.7565231,  7.0458946],
       [ 9.827717 , -4.317215 , -1.4296494]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.94618587,  0.14288542, -0.17464802],
       [ 0.14288542,  0.6206156 ,  0.4637

((3, 3), (6, 3))
(array([[ 0.97840181,  0.14517279,  0.00752167],
       [ 0.14517279,  0.02421761, -0.0505571 ],
       [ 0.00752167, -0.0505571 ,  0.99738054]]), array([[ -7.1872616 ,  -1.4382496 ,   1.1109838 ],
       [ -2.7041435 ,  -0.9239979 ,   9.713369  ],
       [  6.2274647 ,   0.68867683,   5.7445173 ],
       [  7.74074   ,   0.9765301 ,  -2.8873672 ],
       [  0.68894005,   0.7045021 , -10.072975  ],
       [ -5.2277317 ,  -0.46813583,  -5.11487   ]], dtype=float32))
((3, 3), (5, 3))
(array([[ 0.84094243,  0.01794759, -0.36528912],
       [ 0.01794759,  0.99797485,  0.04121815],
       [-0.36528912,  0.04121815,  0.16108268]]), array([[ 11.227713 ,  -4.278123 ,  -5.298004 ],
       [  4.618696 ,   4.7083063,  -1.6271133],
       [ -4.9784393,   6.863653 ,   1.0430756],
       [-10.311682 ,  -5.1534896,   4.7809525],
       [ -0.5646248, -14.270816 ,  -1.4174194]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.97350037,  0.14808241, -0.06220132],
       [ 0.14808241,  0.17

((3, 3), (6, 3))
(array([[ 0.90346394, -0.29519123, -0.00888769],
       [-0.29519123,  0.09735429, -0.02717708],
       [-0.00888769, -0.02717708,  0.99918175]]), array([[-12.178745  ,   1.888485  ,  10.387798  ],
       [ -0.87529755,   0.1189518 ,  13.9087105 ],
       [  9.223     ,  -5.266617  ,   6.5226536 ],
       [  8.505188  ,  -4.134512  ,  -4.2914877 ],
       [  0.26088333,   0.2133255 , -10.215456  ],
       [-10.186199  ,   2.1022224 ,  -4.6321545 ]], dtype=float32))
((3, 3), (7, 3))
(array([[ 0.89755705, -0.30304649,  0.01054582],
       [-0.30304649,  0.10352856,  0.03119661],
       [ 0.01054582,  0.03119661,  0.99891438]]), array([[-11.829697  ,   1.93857   ,  -5.059864  ],
       [-10.4470825 ,   1.888897  ,   5.5833025 ],
       [ -0.26088333,  -0.2133255 ,  10.215456  ],
       [  8.244305  ,  -4.3478374 ,   5.923969  ],
       [  6.8719444 ,  -4.3674297 ,  -4.192088  ],
       [  3.3479538 ,  -2.7823792 ,  -7.942711  ],
       [ -4.5780334 ,   0.523304  , -10.412

       [ -5.448593 ,   4.249319 ,   6.3669415]], dtype=float32))
((3, 3), (7, 3))
(array([[ 0.12324011, -0.01456007,  0.32838997],
       [-0.01456007,  0.99975821,  0.00545347],
       [ 0.32838997,  0.00545347,  0.8770017 ]]), array([[ -4.0417633 ,  11.386496  ,  -3.848568  ],
       [ -0.4557495 ,  13.835448  ,  11.365956  ],
       [  3.814209  ,  -0.14158273,  12.734617  ],
       [  0.924469  ,  -8.666814  ,   7.9602604 ],
       [ -4.4262543 , -11.900459  ,  -1.0324707 ],
       [ -6.66481   ,  -9.9402685 , -11.184872  ],
       [ -7.1293564 ,   3.0848806 , -14.012711  ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.22875714,  0.3347998 ,  0.25364608],
       [ 0.3347998 ,  0.85466199, -0.11010883],
       [ 0.25364608, -0.11010883,  0.91658098]]), array([[-5.9097137, -9.609946 ,  3.0287228],
       [-5.3507233, -3.2336454, -8.992731 ],
       [-0.924469 ,  8.666814 , -7.9602604],
       [ 2.88974  ,  8.525231 ,  4.774357 ],
       [ 2.1943283,  1.4707403,  6.8510485],
       [

Iteration 1 ...
((3, 3), (6, 3))
(array([[ 0.02482033,  0.12304103, -0.09521119],
       [ 0.12304103,  0.98447558,  0.01201305],
       [-0.09521119,  0.01201305,  0.9907041 ]]), array([[  0.28849792,   2.6145794 ,  11.084472  ],
       [  3.2975845 ,   9.966851  ,   5.5761213 ],
       [  4.253044  ,   9.372484  ,  -8.608208  ],
       [  1.5169601 ,  -1.8329554 , -10.973726  ],
       [  2.309288  , -10.612646  ,  -3.2525628 ],
       [  0.09095764,  -7.566289  ,   7.271942  ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 4.09635305e-02, -1.98177412e-01, -3.35344626e-03],
       [-1.98177412e-01,  9.59048185e-01, -6.92963542e-04],
       [-3.35344626e-03, -6.92963542e-04,  9.99988274e-01]]), array([[  2.9045334 ,  -7.3709974 ,   9.168759  ],
       [  0.801033  ,   3.6358628 ,  10.836234  ],
       [  0.19754028,  10.180868  ,   3.8125296 ],
       [ -0.09095764,   7.566289  ,  -7.271942  ],
       [  2.2183304 ,  -3.0463572 , -10.524505  ],
       [  4.3350296 ,  -9.837828  ,  -3.65

/Users/zachcm/opt/miniconda3/envs/pyme/lib/python3.7/site-packages/ipykernel_launcher.py:36: RuntimeWarning: divide by zero encountered in true_divide


((3, 3), (7, 3))
(array([[ 0.39999527, -0.47725379, -0.11057927],
       [-0.47725379,  0.62038434, -0.0879566 ],
       [-0.11057927, -0.0879566 ,  0.97962054]]), array([[  2.2064133 ,   0.23202133, -11.634753  ],
       [  7.5686913 ,  -7.2779074 ,  -8.8402605 ],
       [  9.867542  , -11.099673  ,   0.777544  ],
       [  5.4737167 ,  -8.572026  ,  10.242591  ],
       [ -2.9923782 ,   0.56710815,  10.99019   ],
       [ -5.1090775 ,   7.3585787 ,   4.1248703 ],
       [ -4.50576   ,   7.837078  ,  -7.7844915 ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.35519719,  0.423996  ,  0.22194476],
       [ 0.423996  ,  0.72119758, -0.14594181],
       [ 0.22194476, -0.14594181,  0.92360536]]), array([[-2.8563385,  0.8129978, -9.3094425],
       [-4.809311 , -5.3118067, -5.457592 ],
       [-2.021309 , -8.431213 ,  3.7029667],
       [ 1.7526169, -2.4101381, 10.28162  ],
       [ 6.304741 ,  5.49438  ,  5.351139 ],
       [ 5.1082306,  7.4897394, -5.253725 ]], dtype=float32))
((3, 3), (5

       [  2.4292183 ,  -7.755624  ,  -7.492008  ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.87354241, -0.23599599, -0.23403408],
       [-0.23599599,  0.55958271, -0.43675596],
       [-0.23403408, -0.43675596,  0.56687495]]), array([[-9.972549 ,  7.1954374,  0.7310524],
       [-3.2333298,  7.8905067, -5.1411133],
       [ 6.3895073,  3.2958593, -5.396385 ],
       [10.641663 , -5.0083923,  0.5199623],
       [ 3.4389305, -7.974266 ,  8.478077 ],
       [-8.891758 , -1.4403229,  6.4728203]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.99744301,  0.05049043,  0.00107966],
       [ 0.05049043,  0.00301278, -0.02131895],
       [ 0.00107966, -0.02131895,  0.99954413]]), array([[ 6.8810825 , -0.7035694 ,  3.500473  ],
       [ 7.930393  ,  1.2197247 , -5.1736526 ],
       [-1.3653946 , -0.09876823, -7.468136  ],
       [-9.227093  , -1.1885834 , -4.711117  ],
       [-6.664505  , -0.09914017,  7.280611  ],
       [ 1.0202484 , -0.08636284,  9.715988  ]], dtype=float32))
((3, 3), (6,

       [ -3.6873665 ,   0.3054428 ,  -5.750579  ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.96992127,  0.16622633, -0.03927856],
       [ 0.16622633,  0.08137095,  0.21706802],
       [-0.03927856,  0.21706802,  0.94870778]]), array([[ 4.637293  , -1.7785568 , -5.8333435 ],
       [-2.1880913 , -3.3335629 , -7.0969124 ],
       [-9.426281  , -3.0635204 , -0.55762863],
       [-5.3384705 , -0.32212067,  6.131138  ],
       [ 3.9573174 ,  0.9963722 ,  8.425621  ],
       [ 8.195892  ,  0.9063282 ,  0.894783  ]], dtype=float32))
((3, 3), (4, 3))
(array([[ 0.9905415 , -0.09659878,  0.00614136],
       [-0.09659878,  0.01344615,  0.06272106],
       [ 0.00614136,  0.06272106,  0.99601245]]), array([[-5.469244  ,  0.10900116, -4.316393  ],
       [-4.204893  ,  0.5802593 ,  7.533695  ],
       [ 4.649336  , -0.44564247,  2.5434494 ],
       [ 3.0160809 , -0.92274857, -4.9862003 ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.99709162, -0.05306556,  0.00916356],
       [-0.05306556,  0.

((3, 3), (6, 3))
(array([[ 0.99798927, -0.03901136,  0.02201811],
       [-0.03901136,  0.24311626,  0.42718703],
       [ 0.02201811,  0.42718703,  0.75889459]]), array([[  5.8333483 ,   3.1943855 ,   7.654873  ],
       [ 13.294621  ,  -1.5919418 ,  -1.0099907 ],
       [  6.6186275 ,  -5.527052  ,  -7.392189  ],
       [ -5.7416143 ,  -4.799143  ,  -7.702965  ],
       [-12.453253  ,   0.0546093 ,  -0.33281708],
       [ -7.027089  ,   3.548973  ,   7.296341  ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.99962342,  0.01102767,  0.01596338],
       [ 0.01102767,  0.67706951, -0.46746638],
       [ 0.01596338, -0.46746638,  0.32330698]]), array([[-5.904452 , -4.8088074,  3.7455978],
       [-8.557449 ,  2.54712  , -0.5698242],
       [ 0.7302451,  9.063516 , -5.1362686],
       [11.443965 ,  6.123393 , -2.8345566],
       [12.046712 , -3.0368938,  3.3009872],
       [ 2.453133 , -7.0940742,  6.6111298]], dtype=float32))
((3, 3), (6, 3))
(array([[ 9.99965895e-01, -5.82938921e-03,  3

((3, 3), (6, 3))
(array([[ 0.99544519,  0.01559472,  0.06550475],
       [ 0.01559472,  0.946607  , -0.22427438],
       [ 0.06550475, -0.22427438,  0.05794764]]), array([[ -1.0850852 ,  -8.568775  ,  -1.0801544 ],
       [  6.712472  ,  -5.8164663 ,  -0.91043854],
       [ 12.253909  ,   3.1816773 ,  -3.535942  ],
       [  3.0115998 ,  11.606245  ,  -4.7130737 ],
       [-10.660721  ,   9.84569   ,  -6.877716  ],
       [ -8.914303  ,  -3.6698985 ,  -2.2239838 ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 9.99991009e-01, -2.94634025e-03, -5.57011226e-04],
       [-2.94634025e-03,  3.45159173e-02, -1.82526603e-01],
       [-5.57011226e-04, -1.82526603e-01,  9.65492997e-01]]), array([[  9.610052  ,  -0.98186684,  -1.4548683 ],
       [  5.1891704 ,  -2.645893  ,   7.5630074 ],
       [ -8.616081  ,  -3.2534695 ,  10.957916  ],
       [-10.345427  ,  -1.2466545 ,   0.3967514 ],
       [ -6.190279  ,   0.36772728,  -8.32115   ],
       [  4.5021224 ,   0.5018997 ,  -8.989193  ]], dtype=

       [ 10.368134  ,   0.2602005 ,   2.000681  ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.88753644, -0.24035706, -0.20504633],
       [-0.24035706,  0.48630905, -0.43822488],
       [-0.20504633, -0.43822488,  0.62615454]]), array([[ -9.818817 ,  -2.1423512,   5.3095627],
       [ -1.6590996,  -5.874648 ,   5.04953  ],
       [  6.4422874,  -7.274699 ,   1.2208557],
       [ 12.919807 ,  -2.8377228,  -6.7841682],
       [  2.1997871,   5.9393253, -10.900421 ],
       [-10.988878 ,   5.7386513,  -4.499489 ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.91406797, -0.24786401,  0.13080955],
       [-0.24786401,  0.28505629,  0.37730956],
       [ 0.13080955,  0.37730956,  0.80087592]]), array([[ -5.8739376,  -5.2741795, -10.388123 ],
       [-10.055239 ,   1.8726673,  -1.9733887],
       [ -3.8256226,   2.9207954,   6.7824287],
       [  5.564434 ,   0.6750698,   7.9825516],
       [  7.671398 ,  -2.5475712,   1.0843658],
       [  5.1962547,  -5.7931957,  -4.400074 ]], dtype=floa

((3, 3), (6, 3))
(array([[ 0.18828595,  0.20635289, -0.33204353],
       [ 0.20635289,  0.94754123,  0.08441168],
       [-0.33204353,  0.08441168,  0.86417271]]), array([[ -2.7961807 ,   5.017837  ,   8.240038  ],
       [ -5.047249  ,  -4.7519937 ,   7.4776535 ],
       [ -4.0544205 , -10.044027  ,  -1.2891655 ],
       [  1.4216614 ,  -6.00862   ,  -8.161083  ],
       [  3.3226166 ,   3.4952414 ,  -8.588947  ],
       [  0.41797638,   8.8990555 ,   0.47503662]], dtype=float32))
((3, 3), (5, 3))
(array([[ 0.28311723,  0.44274023,  0.08332448],
       [ 0.44274023,  0.72656769, -0.05146043],
       [ 0.08332448, -0.05146043,  0.99031506]]), array([[-1.2895126 ,  0.33472538, -8.351614  ],
       [ 1.5927811 ,  5.292683  , -4.0417366 ],
       [ 4.0311584 ,  6.2992415 ,  5.588022  ],
       [-0.9232025 , -1.540597  ,  7.973441  ],
       [-5.3507385 , -7.1485395 ,  0.32964015]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.10464138, -0.14889982, -0.26743281],
       [-0.14889982,  0.97

((3, 3), (6, 3))
(array([[ 0.21202093, -0.03070155,  0.40758494],
       [-0.03070155,  0.99880379,  0.01588049],
       [ 0.40758494,  0.01588049,  0.78917527]]), array([[  3.3003845, -12.180858 ,   1.9227104],
       [  5.423687 ,  -3.0176408,   8.197277 ],
       [  3.575264 ,   6.4949274,   3.7765465],
       [ -1.3324661,   8.482459 ,  -5.4495583],
       [ -5.1209717,   2.4105814, -12.009455 ],
       [ -3.7669678,  -9.559065 , -11.268934 ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.54748267,  0.49159023,  0.0780029 ],
       [ 0.49159023,  0.46596313, -0.08473811],
       [ 0.0780029 , -0.08473811,  0.98655421]]), array([[  6.056904 ,   3.8115005,   4.629235 ],
       [  6.278763 ,   4.84972  ,  -5.440176 ],
       [ -1.9465408,  -0.7053776, -11.196621 ],
       [ -8.022453 ,  -8.509591 ,  -3.2945998],
       [ -6.7045517,  -8.35168  ,   6.1270614],
       [  1.2706146,  -1.6765766,  10.193161 ]], dtype=float32))
((3, 3), (7, 3))
(array([[ 0.25387657, -0.19335005, -0.3899218

((3, 3), (5, 3))
(array([[ 0.97551536, -0.15448739,  0.00433412],
       [-0.15448739,  0.02525192,  0.0273464 ],
       [ 0.00433412,  0.0273464 ,  0.9992328 ]]), array([[  2.7266579 ,  -0.5993328 , -12.491948  ],
       [ -7.7631874 ,   0.86533165,  -5.9010715 ],
       [ -7.0768394 ,   1.1814861 ,   6.2841406 ],
       [  3.655346  ,  -0.29444122,   5.734495  ],
       [  7.185684  ,  -1.604065  ,  -3.3575296 ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.96955707, -0.16680259, -0.04114681],
       [-0.16680259,  0.08605713, -0.22545116],
       [-0.04114681, -0.22545116,  0.94438577]]), array([[  2.7500954 ,   3.1916046 , -12.576519  ],
       [  9.473871  ,  -0.65172577,  -3.4691315 ],
       [  7.287613  ,  -1.6383667 ,   5.447666  ],
       [ -3.7187042 ,  -0.44119072,   8.8629875 ],
       [-10.327572  ,   0.8347664 ,   2.9701347 ],
       [-10.883957  ,   4.78487   ,  -6.0338326 ]], dtype=float32))
((3, 3), (7, 3))
(array([[ 9.97992600e-01,  4.47528288e-02,  7.44934776e-04],

       [ 9.439878  , -1.1976242 ,  2.6612453 ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.98139332,  0.13511868,  0.00184697],
       [ 0.13511868,  0.01879007, -0.01341237],
       [ 0.00184697, -0.01341237,  0.99981666]]), array([[-10.44421  ,  -2.0487766,   0.5361428],
       [ -4.3802376,  -0.5900974,  -8.868734 ],
       [  5.030878 ,   0.6243286,  -8.69057  ],
       [  9.868687 ,   0.9338913,  -0.8589787],
       [  5.1767826,   0.2907791,   8.061371 ],
       [ -6.83025  ,  -1.096981 ,   8.282834 ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 9.97711316e-01,  4.77779880e-02,  8.42584937e-04],
       [ 4.77779880e-02,  2.59888172e-03, -1.75895896e-02],
       [ 8.42584937e-04, -1.75895896e-02,  9.99689800e-01]]), array([[-2.3928318e+00,  2.2528458e-01,  1.1798916e+01],
       [-1.3926773e+01, -1.6358948e-01,  4.0162582e+00],
       [-1.2274750e+01, -1.0943527e+00, -6.4988098e+00],
       [-9.4511604e-01,  1.0516987e+00, -1.1603727e+01],
       [ 1.1463111e+01,  6.5023422e-01

((3, 3), (6, 3))
(array([[ 0.99609258, -0.01546196, -0.0604407 ],
       [-0.01546196,  0.93881582, -0.23916855],
       [-0.0604407 , -0.23916855,  0.06509173]]), array([[ 10.732576  ,  -2.9696126 ,   2.3008575 ],
       [ -0.7211617 ,  -9.105284  ,   5.1392136 ],
       [ -9.301264  ,  -6.5470586 ,   4.557495  ],
       [-17.5513    ,   8.349116  ,   1.315567  ],
       [ -1.0002859 ,  12.406109  ,  -0.47878265],
       [  9.611061  ,   6.990645  ,  -0.17918396]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.99881478, -0.03409863, -0.0045931 ],
       [-0.03409863,  0.01898503, -0.13214312],
       [-0.0045931 , -0.13214312,  0.98220027]]), array([[-8.2878714e+00,  2.4728775e-02,  1.1630833e+01],
       [-1.0400682e+01,  7.9478836e-01, -1.8112183e-02],
       [-3.6373415e+00,  3.1618004e+00, -7.0727272e+00],
       [ 3.1144242e+00,  1.6962357e+00, -5.9392662e+00],
       [ 8.2432070e+00,  3.6082458e-01, -4.7420502e-01],
       [ 5.7611008e+00,  4.0245056e-03,  8.6170769e+00]], dtype=

((3, 3), (7, 3))
(array([[ 0.99925041, -0.02731867,  0.00164784],
       [-0.02731867,  0.004372  ,  0.06005548],
       [ 0.00164784,  0.06005548,  0.9963775 ]]), array([[ -8.483824  ,  -0.23492432,  -8.014652  ],
       [ -0.57169104,  -0.8047104 , -10.946671  ],
       [ 10.176613  ,  -0.8639622 ,  -6.733366  ],
       [ 14.545662  ,  -0.4649887 ,   4.910569  ],
       [  3.7984524 ,   0.6305084 ,  10.582913  ],
       [ -5.3355246 ,   0.5025234 ,  10.332962  ],
       [-11.113702  ,   0.05660629,   1.9089231 ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 9.99976137e-01, -4.86038020e-03, -4.89345111e-04],
       [-4.86038020e-03,  1.00584030e-02, -9.96677428e-02],
       [-4.89345111e-04, -9.96677428e-02,  9.89965410e-01]]), array([[-0.4498949 , -1.7316341 , 11.215164  ],
       [ 6.906055  , -1.7722263 ,  6.6512604 ],
       [14.000313  ,  0.04422188, -4.403408  ],
       [ 3.32134   ,  0.13488007, -9.379753  ],
       [-8.342137  , -0.12859344, -7.0574875 ],
       [-8.206372  , -

((3, 3), (6, 3))
(array([[ 0.97598082, -0.15308827,  0.00249633],
       [-0.15308827,  0.0242787 ,  0.01591056],
       [ 0.00249633,  0.01591056,  0.99974055]]), array([[-3.069046  ,  0.8668289 ,  9.722218  ],
       [-8.24567   ,  1.4938622 ,  0.52697563],
       [-6.5031223 ,  1.0040112 , -6.8348513 ],
       [ 3.8684044 , -0.8848076 , -9.971057  ],
       [10.524689  , -1.1918564 , -2.025652  ],
       [ 6.8631706 , -1.1657467 ,  9.972304  ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.97547368, -0.15225723, -0.02724918],
       [-0.15225723,  0.05480069, -0.16916046],
       [-0.02724918, -0.16916046,  0.96972569]]), array([[  0.24904633,  -2.560522  ,   9.516541  ],
       [ 10.861446  ,  -4.8528233 ,   3.9724655 ],
       [ 11.525959  ,  -0.680254  ,  -7.350605  ],
       [  0.9601898 ,   0.79445267, -13.044237  ],
       [ -8.451937  ,   0.8118    ,  -5.8971863 ],
       [-16.082077  ,   0.96842957,   4.3042183 ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.98897501,  0.10

       [ -6.8631706 ,   1.1657467 ,  -9.972304  ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.99478167, -0.07202447,  0.0018904 ],
       [-0.07202447,  0.00590307,  0.02609171],
       [ 0.0018904 ,  0.02609171,  0.99931518]]), array([[ -6.0518913 ,  -0.04922676,  -9.35145   ],
       [-12.1511345 ,  -0.9926853 ,  -1.1440544 ],
       [ -5.0994034 ,  -0.720253  ,   6.041605  ],
       [  2.6137428 ,  -0.47601128,   8.400692  ],
       [  9.880245  ,  -1.7551193 ,   3.08704   ],
       [  5.905285  ,  -2.3660164 ,  -9.046579  ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.99029542,  0.09802031, -0.00155578],
       [ 0.09802031,  0.00995398,  0.01571403],
       [-0.00155578,  0.01571403,  0.99975059]]), array([[ -6.261284  ,   0.24915695, -12.455119  ],
       [  7.362694  ,   0.7329407 ,  -9.471085  ],
       [  8.854992  ,   1.5501385 ,   0.86341286],
       [  3.0274315 ,   1.7804184 ,  11.614365  ],
       [ -6.062172  ,  -0.587265  ,   6.0950165 ],
       [-10.367119  ,  -0.

       [ -2.8945618 ,  -8.556568  ,  -4.7568665 ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.09194511,  0.24235405,  0.15733919],
       [ 0.24235405,  0.93531725, -0.04199282],
       [ 0.15733919, -0.04199282,  0.97273775]]), array([[ 2.3266373 ,  1.0240254 ,  9.638044  ],
       [-1.6078262 , -5.332259  ,  4.058781  ],
       [-2.902237  , -4.9924793 , -4.315713  ],
       [-1.0292282 , -0.5513091 , -6.9009323 ],
       [-0.32172394,  6.5656767 , -9.001844  ],
       [ 1.8004074 ,  8.182018  ,  2.6144485 ]], dtype=float32))
((3, 3), (4, 3))
(array([[ 1.02579296e-01, -3.03402454e-01, -1.91443088e-03],
       [-3.03402454e-01,  8.97424877e-01, -6.47236011e-04],
       [-1.91443088e-03, -6.47236011e-04,  9.99995916e-01]]), array([[-0.5445938 ,  1.858047  , -5.011475  ],
       [-2.4568405 ,  6.684717  , -0.10554373],
       [ 0.849144  , -2.3337276 ,  5.971251  ],
       [ 1.6120834 , -5.3449454 , -0.997363  ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.06471467, -0.24367711, -0

       [-2.6744003, -6.5168533, -5.917387 ]], dtype=float32))
((3, 3), (4, 3))
(array([[ 0.35438776, -0.40884471, -0.24828029],
       [-0.40884471,  0.74109226, -0.15722764],
       [-0.24828029, -0.15722764,  0.90451993]]), array([[-3.5655136,  4.848257 ,  1.6153221],
       [ 1.6676636,  0.2822733, -5.6477203],
       [ 2.8086166, -4.410842 ,  0.2874565],
       [-2.0248566, -1.1213036,  6.2653522]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.49977601, -0.44467178,  0.22861974],
       [-0.44467178,  0.60471112,  0.20323046],
       [ 0.22861974,  0.20323046,  0.89551283]]), array([[ 5.531971  , -1.958704  ,  8.022375  ],
       [ 1.4242783 ,  5.5041437 , 10.386824  ],
       [-5.6512833 ,  8.112318  , -2.7935772 ],
       [-4.266083  , -0.13846397, -8.695982  ],
       [ 3.7756538 , -5.8338947 , -8.86516   ],
       [ 8.621113  , -6.5528507 ,  0.5534706 ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.53574774,  0.47726914,  0.14469387],
       [ 0.47726914,  0.50934899, -0.14875

((3, 3), (6, 3))
(array([[ 0.93412384,  0.22873537,  0.09600318],
       [ 0.22873537,  0.20578432, -0.33334255],
       [ 0.09600318, -0.33334255,  0.86009185]]), array([[  9.763212  ,   1.0786686 ,   3.1007195 ],
       [ 11.27957   ,   3.8023205 ,  -8.141506  ],
       [ -0.5314064 ,   2.8238564 , -12.523815  ],
       [-10.616478  ,  -0.82167435,  -5.7934303 ],
       [ -8.334583  ,  -7.297945  ,   4.225498  ],
       [  1.0192299 ,  -5.66835   ,   8.920883  ]], dtype=float32))
((3, 3), (5, 3))
(array([[ 0.97349923, -0.16055609,  0.00449698],
       [-0.16055609,  0.0272637 ,  0.02724518],
       [ 0.00449698,  0.02724518,  0.9992369 ]]), array([[  2.728693  ,  -0.5961113 , -12.492812  ],
       [ -7.757351  ,   0.95742035,  -5.907427  ],
       [ -7.0429344 ,   1.2530518 ,   6.282324  ],
       [  3.6227684 ,  -0.2838955 ,   5.7183404 ],
       [  7.154743  ,  -1.60215   ,  -3.3659673 ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.96960528, -0.16678098, -0.04068162],
       [-0.

((3, 3), (6, 3))
(array([[ 0.97516973, -0.15519312,  0.01135022],
       [-0.15519312,  0.03001863,  0.07094065],
       [ 0.01135022,  0.07094065,  0.99481168]]), array([[ 5.9849873 , -1.6603146 , -8.845772  ],
       [-4.0134315 ,  0.39879608, -8.757322  ],
       [-8.38884   ,  1.1896057 ,  0.6236687 ],
       [-2.8790436 ,  0.97153854,  5.0045395 ],
       [ 1.7145176 ,  0.5376587 ,  7.5772076 ],
       [ 9.443222  , -1.1871185 ,  2.692192  ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.98063805,  0.13778035,  0.00190818],
       [ 0.13778035,  0.01954979, -0.01357865],
       [ 0.00190818, -0.01357865,  0.99981194]]), array([[-10.379202  ,  -2.121622  ,   0.54708195],
       [ -4.347294  ,  -0.591156  ,  -8.85701   ],
       [  5.028187  ,   0.6218147 ,  -8.693848  ],
       [  9.858038  ,   0.9244652 ,  -0.8492622 ],
       [  5.1848145 ,   0.29128838,   8.103591  ],
       [ -6.7761707 ,  -1.1155586 ,   8.272478  ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.99755616,  0.04

((3, 3), (6, 3))
(array([[ 0.99976191,  0.0121724 , -0.00947984],
       [ 0.0121724 ,  0.37768734,  0.48465601],
       [-0.00947984,  0.48465601,  0.62255076]]), array([[11.245638 ,  2.2198162,  2.411621 ],
       [ 3.3298948,  7.964631 ,  7.265457 ],
       [-7.3406854,  6.178713 ,  5.791046 ],
       [-8.413965 , -1.0409393, -1.433548 ],
       [-5.111954 , -5.160038 , -8.933746 ],
       [ 9.734226 , -3.2340183, -6.6534843]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.99456145,  0.0734572 ,  0.00360647],
       [ 0.0734572 ,  0.00783014, -0.04871183],
       [ 0.00360647, -0.04871183,  0.99760843]]), array([[  6.267177  ,  -0.35172272,   8.299929  ],
       [ -4.1803913 ,  -1.5876846 ,   8.68096   ],
       [-11.912226  ,  -1.5179005 ,   0.8626213 ],
       [ -6.953762  ,  -0.66235733,  -7.7965307 ],
       [  4.900315  ,   0.03992653,  -8.759404  ],
       [ 10.8074665 ,   0.12750816,  -0.6720028 ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 9.99327035e-01, -2.59221513e-02,  7

((3, 3), (6, 3))
(array([[ 9.99502780e-01,  2.22928636e-02,  3.64109583e-05],
       [ 2.22928636e-02,  4.99904156e-04, -1.63248461e-03],
       [ 3.64109583e-05, -1.63248461e-03,  9.99997334e-01]]), array([[14.822329  ,  0.38759804,  2.3690715 ],
       [ 4.6216474 ,  0.13061523, -7.553984  ],
       [-3.9520392 , -0.22850418, -7.4136395 ],
       [-9.061213  , -0.36057472, -2.4375634 ],
       [-6.645546  ,  0.06244087,  7.803051  ],
       [ 7.2682147 , -0.12334824, 11.48507   ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.99913726, -0.02909871,  0.00390647],
       [-0.02909871,  0.01855117,  0.13175857],
       [ 0.00390647,  0.13175857,  0.98231154]]), array([[14.04775   , -0.18215561,  4.143505  ],
       [ 2.8196554 ,  0.9718704 ,  9.934772  ],
       [-4.699069  ,  0.793993  ,  5.5082703 ],
       [-9.6665745 ,  0.01559258, -0.5902195 ],
       [-4.5888624 , -1.4719143 , -9.059563  ],
       [10.836967  , -1.6952133 , -9.912926  ]], dtype=float32))
((3, 3), (6, 3))
(array([[

((3, 3), (6, 3))
(array([[ 0.97370238,  0.15972354,  0.00971879],
       [ 0.15972354,  0.02988923, -0.05902888],
       [ 0.00971879, -0.05902888,  0.99640824]]), array([[-7.136444 , -1.4959316,  1.0842009],
       [-2.6599407, -1.008461 ,  9.760517 ],
       [ 6.3106823,  0.8044472,  5.7427473],
       [ 7.6082287,  1.1266804, -2.8136997],
       [ 0.5565319,  0.8540783, -9.999388 ],
       [-5.2254047, -0.4713955, -5.1673775]], dtype=float32))
((3, 3), (5, 3))
(array([[ 0.84058265,  0.01984732, -0.36552641],
       [ 0.01984732,  0.99752903,  0.04550772],
       [-0.36552641,  0.04550772,  0.16188812]]), array([[ 11.289841 ,  -4.3603506,  -5.376274 ],
       [  4.6916122,   4.6687746,  -1.7030563],
       [ -4.998167 ,   6.9041533,   1.0233383],
       [-10.380489 ,  -5.137849 ,   4.7702484],
       [ -0.627182 , -14.370098 ,  -1.5568542]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.97235036,  0.15137818, -0.06300621],
       [ 0.15137818,  0.17122418,  0.3449508 ],
       [-0.063

((3, 3), (7, 3))
(array([[ 0.98107079,  0.13443376, -0.02232612],
       [ 0.13443376,  0.04526168,  0.1585584 ],
       [-0.02232612,  0.1585584 ,  0.97366738]]), array([[  8.716244  ,   4.5157204 ,   3.7384796 ],
       [  0.6255417 ,   3.8941689 ,  10.098797  ],
       [ -4.846348  ,   1.5206928 ,   7.074032  ],
       [-14.176403  ,   0.43645287,   3.2515259 ],
       [ -8.231312  ,  -0.10376549,  -9.435427  ],
       [  0.20825577,  -0.5491848 , -11.539848  ],
       [  9.31052   ,   1.7779884 ,  -6.018654  ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 9.96736456e-01, -5.70308119e-02, -6.16283389e-04],
       [-5.70308119e-02,  3.37994099e-03, -1.07696233e-02],
       [-6.16283389e-04, -1.07696233e-02,  9.99883622e-01]]), array([[-5.24675   ,  1.0872726 , -8.674586  ],
       [ 4.6629868 , -1.0099258 , -8.417675  ],
       [13.612732  ,  0.39740753,  3.001525  ],
       [ 6.261406  , -0.30834198, 12.444375  ],
       [-4.10466   , -0.45248222, 10.469985  ],
       [-8.868557  ,  

       [ 4.99852   ,  6.946416  , -0.22720146]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.15409333,  0.04783503, -0.35785526],
       [ 0.04783503,  0.99729498,  0.0202363 ],
       [-0.35785526,  0.0202363 ,  0.84861168]]), array([[-2.237732 , -9.882475 , -0.73349  ],
       [ 2.7812347, -5.087869 , -8.213287 ],
       [ 3.1271286,  3.91331  , -7.786381 ],
       [-1.6114426,  9.136696 ,  0.6099434],
       [-3.4364243,  4.4491544,  7.891285 ],
       [-3.152916 , -4.6534033,  5.7698555]], dtype=float32))
((3, 3), (9, 3))
(array([[ 0.20638019, -0.3590723 ,  0.18669374],
       [-0.3590723 ,  0.83753818,  0.08446936],
       [ 0.18669374,  0.08446936,  0.95608155]]), array([[ -4.866455  ,   8.9959    ,  11.941767  ],
       [  2.3370132 ,  -0.43575287,  13.888885  ],
       [  4.2692947 ,  -5.278657  ,   9.001732  ],
       [  4.3099594 , -14.131222  ,   1.3823204 ],
       [  0.49847412, -13.987535  , -11.363969  ],
       [ -3.5749893 ,  -2.4871616 , -15.241338  ],
       [ -5.32

Iteration 4 ...
((3, 3), (6, 3))
(array([[ 0.0243451 ,  0.12592921, -0.08885018],
       [ 0.12592921,  0.98374613,  0.01146802],
       [-0.08885018,  0.01146802,  0.99190866]]), array([[  0.2584381 ,   2.746792  ,  10.953585  ],
       [  3.2304    ,  10.114361  ,   5.5929976 ],
       [  4.163353  ,   9.472063  ,  -8.719183  ],
       [  1.3337936 ,  -1.8525264 , -11.007767  ],
       [  2.0853577 , -10.569904  ,  -3.28917   ],
       [  0.07519531,  -7.5610228 ,   7.2597227 ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 4.08926606e-02, -1.98021457e-01,  2.82616634e-03],
       [-1.98021457e-01,  9.59115632e-01,  5.83502522e-04],
       [ 2.82616634e-03,  5.83502522e-04,  9.99991672e-01]]), array([[  2.9881897 ,  -7.354141  ,   9.1226845 ],
       [  0.75730896,   3.7004848 ,  10.712803  ],
       [  0.1832428 ,  10.307815  ,   3.6938624 ],
       [ -0.07519531,   7.5610228 ,  -7.2597227 ],
       [  2.0101624 ,  -3.0088816 , -10.548893  ],
       [  4.3208923 ,  -9.889768  ,  -3.75

((3, 3), (7, 3))
(array([[ 0.75703098, -0.12774689,  0.40940908],
       [-0.12774689,  0.93283395,  0.21525681],
       [ 0.40940908,  0.21525681,  0.31013507]]), array([[  9.402901  ,   1.6139941 ,   4.5424805 ],
       [  3.9440536 ,   9.322098  ,   1.773468  ],
       [ -3.1495018 ,   7.491615  ,  -1.6684723 ],
       [ -9.889931  ,   6.380425  ,  -5.7811813 ],
       [-10.072544  ,  -4.9205    ,  -9.17075   ],
       [  0.49665833,  -9.616581  ,  -6.254303  ],
       [  7.5749645 ,  -5.5434055 ,   1.4044266 ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.99502976, -0.07031523,  0.00114388],
       [-0.07031523,  0.00523359,  0.0161828 ],
       [ 0.00114388,  0.0161828 ,  0.99973674]]), array([[ 1.2594109 ,  0.4837761 , 11.844126  ],
       [ 5.530018  , -0.26756287,  4.4106884 ],
       [ 8.342041  , -1.2672081 , -0.6008129 ],
       [ 4.3105125 , -0.85302544, -9.396842  ],
       [-6.289734  ,  0.7428551 , -8.817566  ],
       [-8.948673  , -0.12611389,  7.212839  ]], dtype=flo

       [-11.097847  ,   1.6555138 ,   9.366329  ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 9.99062445e-01,  3.05982884e-02, -6.48971356e-04],
       [ 3.05982884e-02,  1.38676167e-03,  2.11799871e-02],
       [-6.48971356e-04,  2.11799871e-02,  9.99550785e-01]]), array([[ -8.233047  ,  -0.40372086,  -7.432285  ],
       [  2.7713952 ,  -0.28852463, -10.083717  ],
       [ 11.437698  ,  -0.04990387,  -1.9607081 ],
       [  5.9769387 ,   0.44965935,   8.590258  ],
       [ -5.9528637 ,  -0.24922371,   9.5248    ],
       [-12.771122  ,  -0.64378357,   0.90068704]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.99980479,  0.01102609, -0.0085789 ],
       [ 0.01102609,  0.37721139,  0.48456314],
       [-0.0085789 ,  0.48456314,  0.62298369]]), array([[11.255705 ,  2.240282 ,  2.4192657],
       [ 3.3299298,  7.98993  ,  7.299408 ],
       [-7.311079 ,  6.2208767,  5.784775 ],
       [-8.410155 , -1.0136013, -1.441719 ],
       [-5.1004896, -5.136263 , -8.954693 ],
       [ 9.777557 , 

((3, 3), (6, 3))
(array([[ 0.98450213, -0.12289113,  0.01246811],
       [-0.12289113,  0.02552849,  0.09886651],
       [ 0.01246811,  0.09886651,  0.98996935]]), array([[ -1.6722546 ,   0.58932114,   7.3728485 ],
       [ -5.7867756 ,   0.59827423,   1.9334383 ],
       [-12.770132  ,   0.53404236,  -3.627674  ],
       [ -1.4157181 ,  -1.825964  , -13.858763  ],
       [ 10.3328705 ,  -1.9331722 ,  -3.1211472 ],
       [  6.4587364 ,  -1.0540524 ,   6.857337  ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.82413784,  0.14362188, -0.35257253],
       [ 0.14362188,  0.88270789,  0.28793645],
       [-0.35257253,  0.28793645,  0.29315448]]), array([[ -9.756853  ,   9.271051  ,   6.372963  ],
       [-10.518232  ,  -3.5742998 ,   1.1984406 ],
       [ -2.3594437 ,  -8.240733  ,  -5.4564476 ],
       [  7.0266476 ,  -6.7322664 ,  -9.483692  ],
       [ 11.960264  ,  10.012296  ,  -3.7984161 ],
       [  0.64779854,  14.400951  ,   1.6079636 ]], dtype=float32))
((3, 3), (6, 3))
(array([[

       [-3.1496735 , -4.6886377 ,  5.782234  ]], dtype=float32))
((3, 3), (9, 3))
(array([[ 0.20717758, -0.36007607,  0.18601112],
       [-0.36007607,  0.83646429,  0.08448065],
       [ 0.18601112,  0.08448065,  0.95635828]]), array([[ -4.9243546 ,   8.96262   ,  11.958093  ],
       [  2.3236008 ,  -0.43497372,  13.89146   ],
       [  4.2760468 ,  -5.2948875 ,   9.023193  ],
       [  4.3229675 , -14.180082  ,   1.3864088 ],
       [  0.51278687, -14.033592  , -11.361514  ],
       [ -3.570633  ,  -2.4990225 , -15.248389  ],
       [ -5.3519287 ,   4.8651943 , -10.391618  ],
       [ -5.503807  ,   7.227997  ,  -3.435031  ],
       [ -6.217102  ,   9.117453  ,   1.7747936 ]], dtype=float32))
((3, 3), (5, 3))
(array([[ 0.278346  , -0.40172368, -0.1987147 ],
       [-0.40172368,  0.77637215, -0.11061867],
       [-0.1987147 , -0.11061867,  0.9452819 ]]), array([[ -1.649353  ,  -3.7562428 ,   7.5167217 ],
       [  3.115471  ,  -8.95476   ,  -0.87477875],
       [  2.7133484 ,  -1.809

       [ -0.28562164,  10.0767765 ,   6.967882  ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.14846921,  0.08604314,  0.34499657],
       [ 0.08604314,  0.99130575, -0.03486026],
       [ 0.34499657, -0.03486026,  0.8602251 ]]), array([[  5.137474  ,  -2.3245988 ,  12.070055  ],
       [  3.8312912 ,   6.228961  ,   6.5020103 ],
       [  1.9942169 ,   8.548185  ,  -3.7037163 ],
       [ -2.7217102 ,   3.2436285 ,  -9.377611  ],
       [ -4.4223785 ,  -4.707412  , -10.172531  ],
       [  1.3777237 , -12.08975   ,   0.75175095]], dtype=float32))
((3, 3), (7, 3))
(array([[ 0.21112883, -0.21514426,  0.34679455],
       [-0.21514426,  0.94132495,  0.09457926],
       [ 0.34679455,  0.09457926,  0.84754615]]), array([[  5.6766357 ,  -8.092619  ,   2.7724953 ],
       [  7.0919113 ,  -2.5740833 ,  13.156435  ],
       [  3.7597504 ,   9.765152  ,  11.318304  ],
       [ -1.3777237 ,  12.08975   ,  -0.75175095],
       [ -5.800102  ,   7.3823385 , -10.924282  ],
       [ -3.5322647 ,  -3.

((3, 3), (7, 3))
(array([[ 0.93257933, -0.21783555,  0.12418855],
       [-0.21783555,  0.29617542,  0.401252  ],
       [ 0.12418855,  0.401252  ,  0.7712453 ]]), array([[ -9.797802 ,  -3.5884686, -10.07357  ],
       [  3.5409718,  -5.007965 , -11.930111 ],
       [ 13.288809 ,  -5.046978 ,  -6.1291695],
       [ 13.927031 ,  -2.1463394,   4.493206 ],
       [  9.760021 ,   3.8057976,  10.47065  ],
       [ -2.5573692,   7.877118 ,   7.592304 ],
       [-10.867756 ,   4.2357044,  -1.1454353]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.86732723, -0.03672998, -0.33722636],
       [-0.03672998,  0.98983144, -0.09335991],
       [-0.33722636, -0.09335991,  0.14284134]]), array([[ -6.043972 ,  -4.40876  ,   4.7758713],
       [-11.383129 ,   4.786501 ,   7.349495 ],
       [ -0.9082947,  11.740199 ,   2.1988297],
       [ 13.431547 ,   5.511629 ,  -2.8553314],
       [  8.94529  ,  -4.694292 ,  -0.5940399],
       [  3.3629074,  -9.0926485,   4.478264 ]], dtype=float32))
((3, 3), (7, 3

((3, 3), (6, 3))
(array([[ 0.98765461,  0.08604814,  0.06920041],
       [ 0.08604814,  0.40023899, -0.48233125],
       [ 0.06920041, -0.48233125,  0.61210644]]), array([[  5.6661377 ,  -5.2421246 ,   6.2483215 ],
       [  7.9057546 ,   0.16651917,   1.257515  ],
       [  6.3278604 ,   5.543297  ,  -6.2515373 ],
       [ -1.4123425 ,   6.3149567 , -12.218655  ],
       [-13.041218  ,   1.9488525 ,  -2.97715   ],
       [ -8.043789  ,  -6.872957  ,   4.3271637 ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.99965611,  0.0183797 ,  0.00244047],
       [ 0.0183797 ,  0.01766324, -0.13043545],
       [ 0.00244047, -0.13043545,  0.98268068]]), array([[ 11.328823  ,   1.6791801 ,  -3.7187996 ],
       [  2.2861576 ,   2.9134445 , -12.482548  ],
       [ -8.239022  ,   1.5446339 ,  -5.265852  ],
       [ -7.45018   ,   0.5867348 ,   3.2160034 ],
       [ -1.2239438 ,   0.04916573,   7.203532  ],
       [  7.4285207 ,   0.40037346,   7.082052  ]], dtype=float32))
((3, 3), (6, 3))
(array([[

       [-8.589064  , -8.239426  ,  0.62043   ]], dtype=float32))
((3, 3), (6, 3))
(array([[ 0.99426473, -0.07538061,  0.0044882 ],
       [-0.07538061,  0.00924754,  0.05898996],
       [ 0.0044882 ,  0.05898996,  0.99648771]]), array([[-1.0752014e+01, -4.4075203e-01, -1.1192017e+00],
       [-6.0453529e+00, -1.0391026e+00,  8.2041969e+00],
       [ 6.0551949e+00, -5.5522919e-03,  9.4106655e+00],
       [ 1.2061890e+01, -2.3107224e+00,  2.5605392e-01],
       [ 3.5946579e+00, -2.4417191e+00, -1.0121185e+01],
       [-5.9219341e+00, -4.6421432e-01, -1.1217964e+01]], dtype=float32))
((3, 3), (6, 3))
(array([[ 9.99734215e-01, -1.62919667e-02, -5.34471299e-04],
       [-1.62919667e-02,  1.34062767e-03, -3.27618383e-02],
       [-5.34471299e-04, -3.27618383e-02,  9.98925221e-01]]), array([[ -9.415697  ,  -0.07607841,   7.1459255 ],
       [ -0.91319275,  -0.82696533,  13.085051  ],
       [ 10.679035  ,  -1.4828224 ,   5.70236   ],
       [  8.624527  ,   0.0355072 ,  -6.223978  ],
       [

Time elapsed = 5.865885019302368 s


In [8]:
recipe.namespace[membrane_name] = mesh
surf_count = 0
layer = TriangleRenderLayer(pipeline, dsname=membrane_name, method='shaded', cmap = ['C', 'M', 'Y', 'R', 'G', 'B'][surf_count % 6])
pymevis.add_layer(layer)

# visgui.RefreshView()

lw update
Disposing of HistLimitsEditor
Disposing of HistLimitsEditor
Creating layers GUI
hl update
hl update
hl update
height:  360
NB best size: wx.Size(200, 360)


In [9]:
# pipeline.dataSources['surf0'].manifold

In [10]:
# np.histogram((mesh.vertices**2).sum(1))
# mesh.vertices[(mesh.vertices**2).sum(1)>5e6]

In [11]:
# %timeit np.zeros(1000,dtype=float)

In [12]:
# a = np.zeros(1000,dtype=float)

In [13]:
# %timeit a[:] = 0

In [14]:
# a = np.random.rand(3)

In [15]:
# %timeit np.linalg.norm(a)

In [16]:
# %timeit math.sqrt(a[0]*a[0]+a[1]*a[1]+a[2]*a[2])

In [17]:
# import math
# mesh.curvature_mean

In [18]:
mesh.curvature_mean

# USE_C = True
# array([-0.08093525, -0.00866504, -0.05240814, -0.08317345,  0.02362632,
#         0.0282525 ,  0.08179444, -0.07506737,  0.02445984,  0.03046935,
#         0.07678507, -0.07827818, -0.05523499, -0.06463801, -0.07142361,
#        -0.03030268,  0.00706602,  0.06293204,  0.06461848, -0.08261433,
#         0.04309087, -0.05650999, -0.06826805,  0.0064371 , -0.07965706,
#        -0.01628881,  0.04309166,  0.09841634, -0.01958373, -0.06741484,
#        -0.00354084, -0.07058869,  0.0691588 ,  0.03701629,  0.08057788,
#         0.01971012, -0.04278345, -0.07242775, -0.05020911,  0.02466571,
#        -0.06187785, -0.02077331, -0.03351416, -0.03336353,  0.08851784,
#        -0.07039419,  0.08185363, -0.02909791, -0.06744048,  0.01885984,
#         0.06063289,  0.02055458, -0.0239396 , -0.08632922,  0.04301541,
#        -0.00720791, -0.08484457, -0.00404598,  0.09438683,  0.01950769,
#        -0.03848492,  0.00961029,  0.06587657,  0.07904686, -0.04026097,
#        -0.05160251, -0.01016031, -0.05673593, -0.06521066, -0.09267251,
#         0.08447719, -0.07383481, -0.06175276, -0.06909902,  0.00688352,
#         0.03621555,  0.03355219,  0.02100973, -0.08660565, -0.05175177,
#        -0.04748538, -0.02071361,  0.07625633, -0.07078882, -0.0435674 ,
#         0.02726529,  0.01767305,  0.05837514, -0.0830881 ,  0.01457721,
#        -0.069427  ,  0.08985449, -0.01046628, -0.05343423, -0.03273922,
#         0.08770038, -0.07218429,  0.06170661, -0.00568324,  0.03658308,
#        -0.06717886, -0.00840327, -0.07135181, -0.08732808,  0.07323299,
#        -0.01228129, -0.02651418, -0.06228235, -0.02979777,  0.05788112,
#        -0.03345646, -0.071762  ,  0.09927414,  0.02641748, -0.0647912 ,
#         0.08614354,  0.07537662, -0.06635574, -0.05567439,  0.05234499,
#        -0.07741752, -0.07451253,  0.08693004, -0.08089539,  0.07983296,
#        -0.08832347,  0.09088987, -0.07708101, -0.01672961,  0.03091072,
#         0.06129769, -0.01242314,  0.00877087,  0.02786648,  0.03394059,
#         0.04077507, -0.08509563,  0.08385628, -0.09071361, -0.07253144,
#         0.0405217 , -0.0529703 , -0.03314061, -0.04890803,  0.06386208,
#        -0.05463498, -0.05359986, -0.018659  ,  0.04514278, -0.09959574,
#        -0.05834518, -0.07485174,  0.03013009,  0.08472608,  0.08357349,
#        -0.02213929,  0.05884042,  0.05390621,  0.06756914,  0.02725145,
#        -0.06414943,  0.00640204,  0.03779678,  0.00140768, -0.06115068,
#        -0.04194108, -0.06085332,  0.07411776,  0.07160696,  0.09709716,
#         0.01686836,  0.02866014, -0.06657949, -0.08150007,  0.08162254,
#         0.01306654, -0.07781316, -0.08183778,  0.02752035, -0.06746855,
#         0.06951303, -0.06760946, -0.06613831, -0.08652143, -0.08547915,
#         0.05873303, -0.00657114,  0.04554096, -0.07454738,  0.05069579,
#         0.09023504, -0.06688145, -0.03482477,  0.08027852, -0.02291005,
#        -0.06470495, -0.07426742,  0.00545914, -0.00863561, -0.02665528,
#        -0.00463695, -0.0873556 , -0.018519  ,  0.03551615,  0.03062377,
#         0.09804794,  0.00381883, -0.0932502 , -0.06188733,  0.05086049,
#         0.0721364 , -0.02069302,  0.00416695, -0.07079443,  0.05338389,
#         0.06568254,  0.08042908,  0.03027539, -0.06486863,  0.07716027,
#         0.03391975,  0.0359735 , -0.03726449, -0.02058276, -0.08122787,
#        -0.08823387, -0.07973181, -0.05974455,  0.03828188, -0.04733035,
#         0.02045708,  0.05217726, -0.07654178,  0.08472406, -0.02698311,
#         0.04361411,  0.02162302,  0.00726681,  0.08632529, -0.058246  ,
#        -0.06104133, -0.05225327, -0.05858645,  0.09340581, -0.08084704,
#         0.08081819, -0.038642  ,  0.00498478,  0.07952358,  0.06866355,
#        -0.02698219, -0.02321153, -0.07417154,  0.08726148,  0.01352412,
#        -0.08048396,  0.07948454, -0.03880492, -0.02691324,  0.05726293,
#         0.07861667,  0.10486388, -0.02598679,  0.01579438, -0.03692278,
#         0.00723103, -0.06538578, -0.02662082, -0.01812587, -0.06560162,
#         0.03222846,  0.07197706,  0.07054387, -0.01513215, -0.02647753,
#        -0.06351474, -0.10204495, -0.05963679,  0.0819872 ,  0.06517402,
#         0.05207862, -0.09205754,  0.0852109 , -0.03847128,  0.08323006,
#        -0.04405168, -0.00524504, -0.05019497, -0.05810152, -0.08223791,
#         0.04446666, -0.08080712, -0.02544208, -0.02551689, -0.083782  ,
#        -0.03862651,  0.07304432, -0.01653309,  0.02793306, -0.08912396,
#        -0.03578584, -0.05224152, -0.05399496, -0.09167258,  0.04739149,
#         0.00336238, -0.02977977, -0.07488061, -0.08363505,  0.01868158,
#         0.04151034, -0.06149033,  0.08001206, -0.08481539, -0.07148408,
#         0.04619648,  0.01436198,  0.08199683,  0.09508887, -0.00028106,
#        -0.07604101,  0.01725764,  0.08656894, -0.00215596, -0.06412864,
#         0.05285272,  0.08367443,  0.07054485,  0.06871039,  0.09339744,
#         0.00262263, -0.09212229,  0.03554989,  0.06016709, -0.04546482,
#        -0.00760843, -0.01414109,  0.0485468 ,  0.02335481, -0.00112268,
#         0.0159213 ,  0.09825272, -0.04633595,  0.00774456,  0.00635282,
#        -0.05727105, -0.07166103, -0.00142968, -0.01785818, -0.08884689,
#        -0.08702911,  0.02108714, -0.00943309,  0.0404896 , -0.09681296,
#        -0.00236784,  0.00256145, -0.05014882, -0.07591031,  0.05089113,
#        -0.08964017, -0.02692856,  0.04751926, -0.05224126,  0.03615098,
#         0.09417605, -0.07753401,  0.03272931,  0.05148353,  0.06574939,
#        -0.01240271, -0.0803483 , -0.04603149,  0.09116818, -0.07083942,
#         0.08302771, -0.03449142,  0.0844564 , -0.03880592,  0.08831375,
#        -0.09417611,  0.08952627, -0.04311355,  0.05866918, -0.03415646,
#        -0.00756662,  0.0321246 ,  0.09669775,  0.08135612, -0.08367465,
#        -0.08592194, -0.06180652, -0.08698735, -0.07821529, -0.00575303,
#        -0.07070479, -0.02285701, -0.05533003,  0.01514282,  0.006276  ,
#         0.06035493, -0.07421799,  0.07870184, -0.05277344,  0.07599598,
#        -0.05463277,  0.09790979, -0.02226079, -0.06744492,  0.02043175,
#        -0.03129497, -0.07282996, -0.03550398, -0.04196176,  0.07233167,
#         0.02441241, -0.01114145,  0.05280567, -0.03975239, -0.06375762,
#         0.11489983,  0.09126773, -0.05827877, -0.08380455,  0.08481377,
#         0.07808687,  0.0555934 , -0.04957557,  0.03697523, -0.05883717,
#        -0.05913805, -0.01319586, -0.08509656,  0.03553954, -0.06951813,
#         0.02587411, -0.05867016, -0.00943386, -0.04883876, -0.01536474,
#        -0.04329799,  0.05153409, -0.08088   , -0.05916921, -0.01284895,
#         0.0421304 ,  0.03493537, -0.06936537, -0.00101822, -0.018182  ,
#        -0.0825088 ,  0.09436246, -0.00377361,  0.09758033,  0.0296257 ,
#        -0.06786688, -0.07612389,  0.06827646,  0.0181724 , -0.04316521,
#        -0.06710073, -0.0634625 ,  0.07469611, -0.01931785,  0.06595237,
#         0.07065263, -0.06322552,  0.05086572,  0.01193244, -0.06757798,
#        -0.06679147,  0.07170361, -0.00012747,  0.04013213,  0.08307393,
#        -0.06271523,  0.05839351,  0.03099809,  0.03282024, -0.07125422,
#         0.06895296, -0.05306197, -0.05726997, -0.02779966,  0.00584183,
#        -0.04773605, -0.00093441, -0.01229028, -0.06634882, -0.08356398,
#        -0.06441096, -0.06856446,  0.01762308, -0.07097671, -0.05300697,
#        -0.07049464, -0.01394118,  0.0614799 , -0.07779179, -0.08781993,
#         0.01981919, -0.08332206,  0.08814541, -0.05526725,  0.09897321,
#         0.07166016, -0.00642368,  0.02407776,  0.06945478,  0.01024565,
#        -0.00929939, -0.05791092,  0.07051352,  0.07582062,  0.00241891,
#         0.01445695, -0.01963145, -0.02136468, -0.09036957, -0.07875299,
#        -0.07406367,  0.00484087, -0.03103768,  0.06924489,  0.08431555,
#         0.03683628, -0.04321797, -0.04256097, -0.04894387], dtype=float32)

array([-2.62214467e-02, -2.72587612e-02, -3.60614061e-02, -3.61204036e-02,
       -2.41830535e-02, -1.74725074e-02, -2.57335380e-02, -3.93339060e-02,
       -3.31552662e-02, -2.46578902e-02, -1.68041755e-02, -2.26666201e-02,
       -3.84093933e-02, -3.03960443e-02, -3.04789059e-02, -2.01291442e-02,
       -2.07032487e-02, -8.26985762e-03, -1.64463725e-02, -2.75381245e-02,
       -1.75250433e-02, -3.19894403e-02, -2.21294984e-02, -3.09483595e-02,
       -3.51280607e-02, -2.40988880e-02, -2.17650197e-02, -1.62678473e-02,
       -2.61969045e-02, -1.58357527e-02, -1.75209474e-02, -2.28826739e-02,
        8.50754790e-04, -1.84255764e-02, -7.41410907e-03, -2.45335326e-02,
       -3.59329022e-02, -1.11603364e-02, -3.14190909e-02, -2.24767122e-02,
       -2.76168957e-02, -2.91771032e-02, -2.55726874e-02, -2.21171882e-02,
       -4.84308414e-03, -2.99446527e-02, -1.74021721e-02, -3.00529823e-02,
       -4.39069010e-02, -2.22997032e-02, -1.62714459e-02, -2.44541094e-02,
       -1.89749338e-02, -

In [19]:
mesh._E

# USE_C = True
# array([4.7888641e+00, 5.5163722e-02, 2.4609184e+00, 5.9960074e+00,
#        4.5915371e-01, 5.7771659e-01, 5.6203232e+00, 5.9462676e+00,
#        5.4938757e-01, 1.0075034e+00, 4.8413677e+00, 5.6176414e+00,
#        3.1395075e+00, 6.4202738e+00, 5.5537248e+00, 6.9729555e-01,
#        4.1530162e-02, 4.3747277e+00, 4.3887320e+00, 5.4079008e+00,
#        1.7928334e+00, 3.2206213e+00, 4.5650330e+00, 3.8700905e-02,
#        6.4191022e+00, 2.1214959e-01, 2.1970956e+00, 6.3070550e+00,
#        2.1168567e-01, 6.2834620e+00, 1.0434327e-02, 5.0348463e+00,
#        4.2337542e+00, 1.0565113e+00, 7.6473565e+00, 3.4533176e-01,
#        2.1613719e+00, 5.9268570e+00, 2.1283567e+00, 3.2090414e-01,
#        6.3735805e+00, 2.6459917e-01, 1.6344637e+00, 6.0198689e-01,
#        6.9923115e+00, 5.7312317e+00, 6.4993458e+00, 9.3252838e-01,
#        6.2460003e+00, 2.2247665e-01, 3.3742809e+00, 3.0010641e-01,
#        2.9398343e-01, 5.7810731e+00, 2.0994046e+00, 3.6968224e-02,
#        5.0750260e+00, 1.8915184e-02, 6.0121322e+00, 2.0741022e-01,
#        2.2418504e+00, 6.3844465e-02, 4.4455948e+00, 6.5713048e+00,
#        1.2375342e+00, 5.6728153e+00, 7.9492465e-02, 2.3099384e+00,
#        3.8939240e+00, 7.0204444e+00, 6.7023602e+00, 5.7257943e+00,
#        2.3921909e+00, 6.4833155e+00, 4.7779266e-02, 1.8623694e+00,
#        8.5267240e-01, 2.9924068e-01, 5.1858435e+00, 3.9653716e+00,
#        2.2095723e+00, 2.8056389e-01, 3.5169144e+00, 5.3895912e+00,
#        1.1251317e+00, 3.8480681e-01, 2.3520139e-01, 5.1364026e+00,
#        4.4558487e+00, 1.6283160e-01, 4.4731321e+00, 4.7917285e+00,
#        1.1163201e-01, 2.9410439e+00, 1.0422636e+00, 5.8669367e+00,
#        4.4271083e+00, 2.9688594e+00, 3.1686243e-02, 1.1614283e+00,
#        5.4524760e+00, 4.4155672e-02, 5.3286810e+00, 5.8269901e+00,
#        5.4955325e+00, 1.3092911e-01, 4.3779945e-01, 4.4724936e+00,
#        7.4028039e-01, 2.0326064e+00, 8.9187032e-01, 5.8781209e+00,
#        7.9340324e+00, 5.5061084e-01, 2.5872090e+00, 6.4098959e+00,
#        7.1977434e+00, 3.8996854e+00, 5.2227812e+00, 2.6616263e+00,
#        5.6114402e+00, 4.8262005e+00, 5.9573045e+00, 4.8177314e+00,
#        8.8942289e+00, 6.6010251e+00, 6.0271688e+00, 7.6346750e+00,
#        1.7964746e-01, 7.7821112e-01, 3.8982661e+00, 1.3144305e-01,
#        4.8631292e-02, 6.0351330e-01, 4.8105320e-01, 1.3071668e+00,
#        7.6774335e+00, 6.7898817e+00, 7.1501188e+00, 5.5690217e+00,
#        1.6183472e+00, 2.0226860e+00, 1.2184782e+00, 2.5106828e+00,
#        3.0033431e+00, 3.4103086e+00, 5.1880207e+00, 2.9101086e-01,
#        1.7480634e+00, 6.1576080e+00, 4.7578068e+00, 3.2040255e+00,
#        6.0393357e-01, 8.3596439e+00, 6.9313936e+00, 2.9909039e-01,
#        3.1799836e+00, 3.0187314e+00, 4.7523150e+00, 3.9413416e-01,
#        4.9142513e+00, 2.1291757e-02, 9.3232661e-01, 1.2416546e-03,
#        5.3798480e+00, 1.5844427e+00, 5.7345781e+00, 4.7131648e+00,
#        5.1592126e+00, 7.4231801e+00, 3.1074297e-01, 6.2208301e-01,
#        4.8657894e+00, 5.7961779e+00, 5.1572022e+00, 1.5605068e-01,
#        8.2143745e+00, 6.3644390e+00, 3.8476819e-01, 3.4241292e+00,
#        1.9917096e+00, 5.5379872e+00, 5.4045706e+00, 4.8526483e+00,
#        4.5790191e+00, 3.7781124e+00, 3.0609546e-02, 1.2406043e+00,
#        8.4874172e+00, 3.5463820e+00, 5.8418164e+00, 3.6798964e+00,
#        1.0550048e+00, 4.4712586e+00, 3.2192913e-01, 4.5611644e+00,
#        6.5850339e+00, 3.3780396e-02, 5.3841241e-02, 7.8765702e-01,
#        1.0542242e-02, 7.4172421e+00, 2.4617361e-01, 7.8218269e-01,
#        4.0739399e-01, 6.3738732e+00, 9.6686445e-03, 5.3345094e+00,
#        3.0354149e+00, 1.6131656e+00, 5.4176521e+00, 3.5381594e-01,
#        1.6288713e-02, 3.6858790e+00, 4.0028548e+00, 4.7986050e+00,
#        6.2621160e+00, 4.3108308e-01, 4.8000193e+00, 5.4925661e+00,
#        9.8713440e-01, 6.7568588e-01, 1.2393075e+00, 2.7862063e-01,
#        5.6362381e+00, 6.6966958e+00, 5.5283189e+00, 3.6817458e+00,
#        1.1941537e+00, 1.0477135e+00, 3.6963153e-01, 1.2314720e+00,
#        6.1418896e+00, 6.4563394e+00, 6.5189058e-01, 1.0846916e+00,
#        2.3305391e-01, 6.1961710e-02, 7.3287172e+00, 3.6886728e+00,
#        3.4563589e+00, 3.0157871e+00, 2.0634952e+00, 4.3006420e+00,
#        6.8053617e+00, 6.7828703e+00, 5.0602371e-01, 2.3514900e-02,
#        5.5874186e+00, 4.9511375e+00, 4.7732851e-01, 2.4739914e-01,
#        3.7430487e+00, 5.5713706e+00, 1.1399606e-01, 3.6199925e+00,
#        5.8577747e+00, 1.3284577e+00, 6.1506194e-01, 3.4543254e+00,
#        5.1167054e+00, 5.6580682e+00, 4.3937865e-01, 1.8910123e-01,
#        3.7358674e-01, 2.5920989e-02, 3.5059638e+00, 4.5581210e-01,
#        1.7279543e-01, 4.1814322e+00, 8.6622488e-01, 4.3185325e+00,
#        5.7583427e+00, 1.8583532e-01, 2.9814109e-01, 4.8372250e+00,
#        6.6501174e+00, 6.3159847e+00, 6.3922935e+00, 4.6823802e+00,
#        1.6821775e+00, 5.2749057e+00, 3.4202728e+00, 1.4020994e+00,
#        6.0857739e+00, 1.8745296e+00, 1.4820901e-02, 1.6015474e+00,
#        4.0075908e+00, 3.3238623e+00, 1.3513401e+00, 6.1576443e+00,
#        3.9349312e-01, 4.3504477e-01, 4.6195674e+00, 1.1971551e+00,
#        4.0746531e+00, 1.7835227e-01, 5.8356440e-01, 6.4687662e+00,
#        7.0849180e-01, 1.7079788e+00, 1.8010213e+00, 5.8319793e+00,
#        2.3150897e+00, 7.3625427e-03, 7.0159650e-01, 3.0985243e+00,
#        5.9485397e+00, 1.9744056e-01, 7.3025990e-01, 2.9512348e+00,
#        5.6626897e+00, 7.2472491e+00, 5.5497370e+00, 1.3266283e+00,
#        1.0016703e-01, 5.5462346e+00, 6.0535793e+00, 6.0337716e-05,
#        3.4725399e+00, 2.2525443e-01, 6.1125011e+00, 2.4116500e-03,
#        3.0946944e+00, 3.2320218e+00, 4.8905325e+00, 2.8010314e+00,
#        3.1674988e+00, 5.9061852e+00, 6.6142012e-03, 6.7844467e+00,
#        9.3697208e-01, 3.2905097e+00, 2.0228808e+00, 3.2543406e-02,
#        1.1731124e-01, 1.9703403e+00, 2.3575327e-01, 9.1559370e-04,
#        1.5226397e-01, 6.8949986e+00, 9.9924386e-01, 3.6903366e-02,
#        3.5914462e-02, 3.6451628e+00, 5.3019094e+00, 1.1162981e-03,
#        2.0982702e-01, 4.3668904e+00, 5.0719481e+00, 2.4509613e-01,
#        5.2890513e-02, 1.5135165e+00, 5.8030586e+00, 4.3381937e-03,
#        6.6354489e-03, 2.3320005e+00, 4.8965917e+00, 2.0596447e+00,
#        5.0604062e+00, 6.7511356e-01, 1.7766107e+00, 1.4944606e+00,
#        1.1241276e+00, 5.0429959e+00, 5.1474042e+00, 6.4414096e-01,
#        1.5391073e+00, 5.3933825e+00, 1.8565731e-01, 6.3890324e+00,
#        2.8417873e+00, 5.3183866e+00, 7.2993217e+00, 4.3230224e+00,
#        6.8367130e-01, 7.4911723e+00, 1.5951272e+00, 5.1900702e+00,
#        6.2257347e+00, 7.2067041e+00, 1.8536645e+00, 3.2579772e+00,
#        6.5672177e-01, 4.0172826e-02, 7.1001726e-01, 4.4357443e+00,
#        5.7220354e+00, 6.7560086e+00, 4.8456450e+00, 4.5447240e+00,
#        7.8404932e+00, 5.8395109e+00, 1.9648816e-02, 3.5543735e+00,
#        3.2369775e-01, 2.1804934e+00, 1.1610789e-01, 3.7543837e-02,
#        4.4419346e+00, 5.5287800e+00, 9.0927095e+00, 1.9117446e+00,
#        4.5217886e+00, 4.3285542e+00, 5.2483411e+00, 4.0475821e-01,
#        5.5676084e+00, 2.3994777e-01, 5.2919698e-01, 7.6824365e+00,
#        1.2498093e+00, 1.8211323e+00, 5.7286735e+00, 4.7155708e-01,
#        1.0708101e-01, 3.0948668e+00, 2.2989216e+00, 4.6216631e+00,
#        7.9341006e+00, 7.1694889e+00, 2.1236026e+00, 5.0210338e+00,
#        5.9339161e+00, 8.2365780e+00, 2.1767502e+00, 2.0641515e+00,
#        6.3958985e-01, 4.7347784e+00, 2.4467101e+00, 1.6105385e-01,
#        5.4718084e+00, 1.3814777e+00, 3.0669723e+00, 5.3356999e-01,
#        5.6617999e+00, 7.8793593e-02, 3.8679154e+00, 2.3980786e-01,
#        1.5452495e+00, 2.4605474e+00, 6.9061947e+00, 3.9578731e+00,
#        1.7962563e-01, 1.5172926e+00, 1.3399053e+00, 8.6872663e+00,
#        8.9673186e-04, 3.2573292e-01, 5.2483244e+00, 6.4858694e+00,
#        1.2081514e-02, 9.5184040e+00, 9.4634658e-01, 6.3570061e+00,
#        4.6511669e+00, 5.5561409e+00, 2.3963203e-01, 2.2582257e+00,
#        6.0072484e+00, 4.2237816e+00, 5.4450712e+00, 2.9700810e-01,
#        4.9449339e+00, 5.7972174e+00, 5.0329504e+00, 2.7869678e+00,
#        6.4310014e-02, 5.1839204e+00, 5.0321693e+00, 4.2546315e+00,
#        1.7473945e-05, 1.5971855e+00, 6.7981644e+00, 4.1990185e+00,
#        3.3182998e+00, 1.1265223e+00, 9.9894416e-01, 4.8688936e+00,
#        4.8652844e+00, 1.8973892e+00, 5.5260196e+00, 7.4000776e-01,
#        3.2403495e-02, 1.8670808e+00, 8.1452972e-04, 1.7924352e-01,
#        4.3902774e+00, 6.4868588e+00, 1.9062065e+00, 5.7808557e+00,
#        1.3373585e-01, 5.9885664e+00, 5.4330549e+00, 5.2087989e+00,
#        1.6815184e-01, 4.5803266e+00, 4.8934050e+00, 6.0131645e+00,
#        1.5008712e-01, 5.9726653e+00, 4.6549406e+00, 5.4572358e+00,
#        8.3203640e+00, 3.1516047e+00, 1.8621525e-02, 3.1906304e-01,
#        6.3926764e+00, 7.2744198e-02, 9.5846914e-02, 3.5491152e+00,
#        7.6704240e+00, 6.5159130e+00, 5.4318267e-03, 1.8654837e-01,
#        2.4540196e-01, 4.4106895e-01, 5.5985651e+00, 4.8126459e+00,
#        5.2100210e+00, 1.7650893e-02, 1.2904117e+00, 7.3641219e+00,
#        4.5413737e+00, 1.3220084e+00, 1.7084887e+00, 2.7827485e+00,
#        3.5485535e+00], dtype=float32)


array([2.46787116e-01, 2.47941345e-01, 3.36384714e-01, 4.32977796e-01,
       2.13996917e-01, 9.80279818e-02, 1.19912922e-01, 5.04601777e-01,
       3.85620475e-01, 2.20272273e-01, 9.93576571e-02, 1.94013923e-01,
       4.53634501e-01, 2.44838700e-01, 3.74239534e-01, 1.34322107e-01,
       2.03720510e-01, 3.02200150e-02, 7.17248246e-02, 1.67022407e-01,
       7.75033310e-02, 3.48136932e-01, 1.14735320e-01, 3.54066074e-01,
       3.51299793e-01, 2.34463856e-01, 1.11635655e-01, 6.60694614e-02,
       2.49844253e-01, 7.63049126e-02, 1.14134781e-01, 1.34498253e-01,
       5.19682872e-05, 1.00484177e-01, 1.43544124e-02, 2.52220154e-01,
       2.95885712e-01, 3.49529050e-02, 3.73657137e-01, 1.35924205e-01,
       1.60210684e-01, 1.96259141e-01, 1.76827878e-01, 1.42337918e-01,
       6.32555643e-03, 4.13961858e-01, 8.15963745e-02, 2.93298602e-01,
       6.64186120e-01, 1.32330030e-01, 8.13559443e-02, 2.39523023e-01,
       7.74211138e-02, 1.14287555e-01, 1.62742570e-01, 2.03694537e-01,
      

In [20]:
np.any(np.isnan(mesh._vertices['position']))

False

ERROR:traitsui.wx.toolkit:Wx control <traitsui.wx.helper.TraitsUIPanel object at 0x7f86eb71e4b0> not destroyed cleanly
Traceback (most recent call last):
  File "/Users/zachcm/opt/miniconda3/envs/pyme/lib/python3.7/site-packages/traitsui/wx/toolkit.py", line 436, in _destroy_control
    control.Destroy()
  File "/Users/zachcm/opt/miniconda3/envs/pyme/lib/python3.7/site-packages/traitsui/wx/helper.py", line 326, in Destroy
    self.Unbind(wx.EVT_CHILD_FOCUS)
  File "/Users/zachcm/opt/miniconda3/envs/pyme/lib/python3.7/site-packages/wx/core.py", line 1416, in _EvtHandler_Unbind
    return event.Unbind(self, id, id2, handler)
  File "/Users/zachcm/opt/miniconda3/envs/pyme/lib/python3.7/site-packages/wx/core.py", line 1485, in Unbind
    success += int(target.Disconnect(id1, id2, et, handler))
RuntimeError: wrapped C/C++ object of type TraitsUIPanel has been deleted
ERROR:traitsui.wx.toolkit:Wx control <traitsui.wx.helper.TraitsUIPanel object at 0x7f86ea744550> not destroyed cleanly
Traceb

Ev Idle
('points', 't')
refreshed


In [24]:
p = np.array([[ 0.02505749,  0.12222194, -0.09742415],
       [ 0.12222194,  0.98467786,  0.01221341],
       [-0.09742415,  0.01221341,  0.99026459]]), 
nvs = np.array([[  0.2993393 ,   2.5652542 ,  11.128048  ],
       [  3.321083  ,   9.913801  ,   5.5698614 ],
       [  4.2859726 ,   9.334961  ,  -8.56844   ],
       [  1.5804443 ,  -1.8268723 , -10.960474  ],
       [  2.3833847 , -10.620859  ,  -3.2391427 ],
       [  0.09584808,  -7.5688214 ,   7.2764854 ]], dtype=np.float32)

In [28]:
np.dot(p,-nvs.T).T[0]

array([[  0.76310957],
       [ -2.69844627],
       [-11.02187946]])

In [31]:
-0.02505749*0.2993393-0.12222194*2.5652542+0.09742415*11.128048 

0.7631095811256949

In [32]:
-0.12222194*0.2993393-0.98467786*2.5652542-0.01221341*11.128048 

-2.6984462586999336

In [33]:
0.09742415*0.2993393-0.01221341*2.5652542-0.99026459*11.128048 

-11.021879514655046

ERROR:traits:Exception occurred in traits notification handler for object: <PYME.LMVis.layers.pointcloud.PointCloudRenderLayer object at 0x7f86e8539ad0>, trait: visible, old value: True, new value: False
Traceback (most recent call last):
  File "/Users/zachcm/opt/miniconda3/envs/pyme/lib/python3.7/site-packages/traits/trait_notifiers.py", line 522, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/Users/zachcm/opt/miniconda3/envs/pyme/lib/python3.7/site-packages/traits/trait_notifiers.py", line 484, in dispatch
    handler(*args)
  File "/Users/zachcm/Code/python-microscopy/PYME/LMVis/layers/pointcloud.py", line 120, in <lambda>
    self.on_trait_change(lambda: self.on_update.send(self), 'visible')
  File "/Users/zachcm/Code/python-microscopy/PYME/contrib/dispatch/dispatcher.py", line 174, in send
    for receiver in self._live_receivers(sender)
  File "/Users/zachcm/Code/python-microscopy/PYME/contrib/dispatch/dispatcher.py", line 174, in <listcomp>
    for receive

hl update


ERROR:traits:Exception occurred in traits notification handler for object: <PYME.LMVis.layers.mesh.TriangleRenderLayer object at 0x7f86eb72a5f0>, trait: visible, old value: True, new value: False
Traceback (most recent call last):
  File "/Users/zachcm/opt/miniconda3/envs/pyme/lib/python3.7/site-packages/traits/trait_notifiers.py", line 522, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/Users/zachcm/opt/miniconda3/envs/pyme/lib/python3.7/site-packages/traits/trait_notifiers.py", line 484, in dispatch
    handler(*args)
  File "/Users/zachcm/Code/python-microscopy/PYME/ui/layerFoldPanel.py", line 98, in _refresh
    self.Refresh()
RuntimeError: wrapped C/C++ object of type LayerCaptionBar has been deleted
ERROR:traits:Exception occurred in traits notification handler for object: <PYME.LMVis.layers.mesh.TriangleRenderLayer object at 0x7f86eb72a5f0>, trait: visible, old value: False, new value: True
Traceback (most recent call last):
  File "/Users/zachcm/opt/minico