In [1]:
%gui wx

from PYME.LMVis import VisGUI

/Users/zachcm/opt/miniconda3/envs/pyme/lib/python3.7/_collections_abc.py:702: MatplotlibDeprecationWarning: The global colormaps dictionary is no longer considered public API.
  return len(self._mapping)
/Users/zachcm/opt/miniconda3/envs/pyme/lib/python3.7/_collections_abc.py:720: MatplotlibDeprecationWarning: The global colormaps dictionary is no longer considered public API.
  yield from self._mapping
/Users/zachcm/Code/python-microscopy/PYME/misc/extraCMaps.py:73: MatplotlibDeprecationWarning: 
The revcmap function was deprecated in Matplotlib 3.2 and will be removed two minor releases later. Use Colormap.reversed() instead.
  cmapdat_r = cm.revcmap(ndat[cmapname])
INFO:OpenGL.acceleratesupport:No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'


Trying to load 3rd party recipe module ch_shrinkwrap.recipe_modules.surface_fitting
Loaded 3rd party recipe module ch_shrinkwrap.recipe_modules.surface_fitting
quaternion module not found, disabling custom clip plane orientations
quaternion module not found, disabling custom clip plane orientations


In [2]:
# Delay so wx can boot up
import time
time.sleep(8)

In [3]:
pymevis = VisGUI.ipython_pymevisualize()
pipeline = pymevis.pipeline
recipe = pipeline.recipe

DEBUG:PYME.LMVis.visCore:Creating VisGUI menu bar
DEBUG:PYME.LMVis.Extras:Initializing QPobjectSegment plugin
DEBUG:PYME.LMVis.Extras:Initializing animation plugin
DEBUG:PYME.LMVis.Extras:Initializing clusterAnalysis plugin
DEBUG:PYME.LMVis.Extras:Initializing dockedPanel plugin
DEBUG:PYME.LMVis.Extras:Initializing extra_layers plugin
DEBUG:PYME.LMVis.Extras:Initializing fiducial plugin
DEBUG:PYME.LMVis.Extras:Initializing flagZMotionArtifacts plugin
DEBUG:root:Adding menu items for event filters
DEBUG:PYME.LMVis.Extras:Initializing fusionUtils plugin
DEBUG:PYME.LMVis.Extras:Initializing multiColourAnalysis plugin
DEBUG:PYME.LMVis.Extras:Initializing multiviewMapping plugin
DEBUG:root:Adding menu items for multi-view manipulation
DEBUG:PYME.LMVis.Extras:Initializing objectMeasurements plugin
DEBUG:PYME.LMVis.Extras:Initializing particleTracking plugin
DEBUG:PYME.LMVis.Extras:Initializing perFrameVariable plugin
DEBUG:PYME.LMVis.Extras:Initializing photophysics plugin
DEBUG:PYME.LMVis.E

New Canvas
Saved Views are deprecated -  use the ones with animation instead and remove me!


/Users/zachcm/Code/python-microscopy/PYME/LMVis/filterPane.py:111: wxPyDeprecationWarning: Call to deprecated item. Use InsertItem instead.
  ind = self.lFiltKeys.InsertStringItem(ind+1, key)
/Users/zachcm/Code/python-microscopy/PYME/LMVis/filterPane.py:112: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 1, '%3.2f' % value[0])
/Users/zachcm/Code/python-microscopy/PYME/LMVis/filterPane.py:113: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 2, '%3.2f' % value[1])


Creating fold panel
GenPanels
Creating datasource panel
RecipeView._layout
Input datasources:  []
Image list size: 1
Creating layers GUI
height:  0
NB best size: wx.Size(200, 0)
RecipeView._layout
Input datasources:  []
RecipeView._layout
Input datasources:  []
0
OpenGL - Version: b'2.1 INTEL-14.7.8'
Shader - Version: b'1.20'


/Users/zachcm/Code/python-microscopy/PYME/LMVis/filterPane.py:111: wxPyDeprecationWarning: Call to deprecated item. Use InsertItem instead.
  ind = self.lFiltKeys.InsertStringItem(ind+1, key)
/Users/zachcm/Code/python-microscopy/PYME/LMVis/filterPane.py:112: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 1, '%3.2f' % value[0])
/Users/zachcm/Code/python-microscopy/PYME/LMVis/filterPane.py:113: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 2, '%3.2f' % value[1])
DEBUG:PYME.LMVis.shader_programs.ShaderProgramFactory:New shader program created: <class 'PYME.LMVis.shader_programs.DefaultShaderProgram.DefaultShaderProgram'>


GL_MAX_SAMPLES: 8, GL_SAMPLES: 4


/Users/zachcm/Code/python-microscopy/PYME/ui/manualFoldPanel.py:37: wxPyDeprecationWarning: Using deprecated class. Use Colour instead.
  col = wx.NamedColour(col)


In [4]:
from ch_shrinkwrap import shape
from PYME.IO import tabular
import numpy as np

# Create a torus
R = 50
r = 30
# t = shape.Torus(R, r)
# pts_t = t.points(1)
pts_t = np.load('hemo_pts.npy')

# Create a bounding box
# import numpy as np
# pts_t = np.vstack([pts_t, np.array([-2*R,-2*R,-2*R]), np.array([2*R,2*R,2*R])])

pipeline.addDataSource('points', tabular.mappingFilter({'x' : pts_t[:,0], 'y':pts_t[:,1], 'z':pts_t[:,2]}))
pipeline.selectDataSource('points')
pymevis.add_pointcloud_layer(ds_name='points')

/Users/zachcm/Code/python-microscopy/PYME/IO/tabular.py:48: VisibleDeprecationWarning: mappingFilter is deprecated, use MappingFilter instead
  warnings.warn(VisibleDeprecationWarning('%s is deprecated, use %s instead' % (name, cls.__name__)))
/Users/zachcm/Code/python-microscopy/PYME/IO/tabular.py:928: VisibleDeprecationWarning: Mapping filter created with something that is not a tabular object. This will be unsupported in a future release. Consider DictSource or ColumnSource instead
  warnings.warn(VisibleDeprecationWarning('Mapping filter created with something that is not a tabular object. This will be unsupported in a future release. Consider DictSource or ColumnSource instead'))
DEBUG:PYME.LMVis.shader_programs.ShaderProgramFactory:New shader program created: <class 'PYME.LMVis.shader_programs.DefaultShaderProgram.OpaquePointShaderProgram'>


lw update
lw update
Creating layers GUI


/Users/zachcm/Code/python-microscopy/PYME/LMVis/layers/base.py:65: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  self.shader_program.v_matrix[3,:3] = -np.linalg.lstsq(gl_canvas.object_rotation_matrix[:3,:3], gl_canvas.view.translation)[0]
DEBUG:PYME.LMVis.visCore:Added layer, datasouce=points


hl update
height:  308
NB best size: wx.Size(243, 308)


In [5]:
# Surface generation parameters
threshold_density = 0.005
# threshold_density = 0.0001
n_points_min = 50
# n_points_min = 100
repair = False
remesh = False

# Run surface generation recipe on the point cloud
from PYME.LMVis.Extras import extra_layers
from PYME.LMVis.layers.mesh import TriangleRenderLayer
from PYME.recipes.surface_fitting import DualMarchingCubes
from ch_shrinkwrap import _membrane_mesh as membrane_mesh

# oc_name = extra_layers.gen_octree_from_points(pymevis)
surf_name, surf_count = pipeline.new_ds_name('surf', return_count=True)
# dmc = DualMarchingCubes(recipe, invalidate_parent=False, input=oc_name, output=surf_name, threshold_density=threshold_density, n_points_min=n_points_min, repair=repair, remesh=remesh)
# recipe.add_module(dmc)
# recipe.execute()
# layer = TriangleRenderLayer(pipeline, dsname=surf_name, method='shaded', cmap = ['C', 'M', 'Y', 'R', 'G', 'B'][surf_count % 6])
# pymevis.add_layer(layer)
# dmc._invalidate_parent = True
mesh = membrane_mesh.MembraneMesh.from_stl('hemo.stl')
pipeline.dataSources[surf_name] = mesh
layer = TriangleRenderLayer(pipeline, dsname=surf_name, method='shaded', cmap = ['C', 'M', 'Y', 'R', 'G', 'B'][surf_count % 6])
pymevis.add_layer(layer)

DEBUG:PYME.LMVis.shader_programs.ShaderProgramFactory:New shader program created: <class 'PYME.LMVis.shader_programs.GouraudShaderProgram.GouraudShaderProgram'>


Data munged to vertices, faces
initializing halfedges ...
vertices.shape = (529, 3), faces.shape = (1054, 3)
iterating edges
done initializing halfedges
lw update
Disposing of HistLimitsEditor
Creating layers GUI
hl update


/Users/zachcm/Code/python-microscopy/PYME/ui/layerFoldPanel.py:47: wxPyDeprecationWarning: Call to deprecated item BitmapFromBuffer. Use :meth:`wx.Bitmap.FromBuffer` or :meth:`wx.Bitmap.FromBufferAndAlpha` instead.
  return wx.BitmapFromBuffer(30, 10, img)
/Users/zachcm/Code/python-microscopy/PYME/ui/histLimits.py:289: wxPyDeprecationWarning: Call to deprecated item EmptyBitmap. Use :class:`wx.Bitmap` instead
  MemBitmap = wx.EmptyBitmap(s.GetWidth(), s.GetHeight())


hl update
height:  335
NB best size: wx.Size(200, 335)


In [6]:
# Shrinkwrapping parameters
max_iters = 1
step_size = 0.1
attraction_weight = 1  # eV/nm
curvature_weight = 1
largest_component_only = True
method = 'euler'
remesh_every = 500  # iterations

In [7]:
from PYME.util import mProfile
import time

# mProfile.profileOn(['_membrane_mesh.pyx'])

# Run surface meshing on the point cloud
membrane_name = pipeline.new_ds_name('membrane')

points_name = 'points'

mesh = membrane_mesh.MembraneMesh(mesh=recipe.namespace[surf_name])
mesh.a = attraction_weight
mesh.c = curvature_weight
mesh.max_iter = 10
mesh.step_size = step_size
# mesh.keep_largest_connected_component()
# mesh.kg = 0

pts = np.ascontiguousarray(np.vstack([recipe.namespace[points_name]['x'], 
                                      recipe.namespace[points_name]['y'],
                                      recipe.namespace[points_name]['z']]).T)

try:
    sigma = recipe.namespace[points_name]['sigma']
except(KeyError):
    sigma = np.ones_like(recipe.namespace[points_name]['x'])
    
residuals = []
res_prev = 1e10
mesh_prev = membrane_mesh.MembraneMesh(mesh=mesh)
start = time.time()
for _i in range(max_iters):
    print('Iteration {} <<<'.format(_i))
    mesh.shrink_wrap(pts, sigma, method=method)
    if ((_i+1) % remesh_every) == 0:
        mesh.remesh()
#     comparison_points = mesh._vertices['position'][mesh._vertices['halfedge']!=-1]
#     new_res = s.surface_res(comparison_points)
#     residuals.append(new_res)
stop = time.time()
print('Time elapsed = {} s'.format(stop-start))
# mProfile.profileOff()
# mProfile.report()

Iteration 0 <<<
Iteration 0 ...
[[ 0.07926639 -0.00993709  0.00792094]
 [ 0.07877965  0.01628242  0.00044785]
 [ 0.100711   -0.02275153 -0.00894907]
 ...
 [-0.08437813 -0.00621842 -0.01475665]
 [-0.11836684 -0.00604726  0.01501848]
 [-0.15188909  0.03227209 -0.00047782]]
Iteration 1 ...


/Users/zachcm/opt/miniconda3/envs/pyme/lib/python3.7/site-packages/ipykernel_launcher.py:34: RuntimeWarning: divide by zero encountered in true_divide


[[ 0.07751907 -0.00978079  0.00756854]
 [ 0.07839308  0.01619932  0.00027412]
 [ 0.10017643 -0.02243646 -0.00873332]
 ...
 [-0.08440713 -0.00607946 -0.01473315]
 [-0.11546948 -0.00560741  0.01429952]
 [-0.14710474  0.03123882 -0.00057343]]
Iteration 2 ...
[[ 7.58217052e-02 -9.63435788e-03  7.23227719e-03]
 [ 7.80299157e-02  1.61199942e-02  1.03209146e-04]
 [ 9.96072441e-02 -2.21183747e-02 -8.52334872e-03]
 ...
 [-8.43767747e-02 -5.93734113e-03 -1.47093823e-02]
 [-1.12435475e-01 -5.18069230e-03  1.35797523e-02]
 [-1.42367333e-01  3.02150268e-02 -6.72188529e-04]]
Iteration 3 ...
[[ 7.4179187e-02 -9.4975941e-03  6.9129160e-03]
 [ 7.7691711e-02  1.6045362e-02 -6.4374035e-05]
 [ 9.9004686e-02 -2.1797776e-02 -8.3189551e-03]
 ...
 [-8.4285766e-02 -5.7925209e-03 -1.4684657e-02]
 [-1.0928017e-01 -4.7684093e-03  1.2862574e-02]
 [-1.3768955e-01  2.9203108e-02 -7.7405013e-04]]
Iteration 4 ...
[[ 0.07259515 -0.00936996  0.00661104]
 [ 0.07737799  0.0159758  -0.00022801]
 [ 0.09837443 -0.02147693 -0

In [8]:
recipe.namespace[membrane_name] = mesh
surf_count = 0
layer = TriangleRenderLayer(pipeline, dsname=membrane_name, method='shaded', cmap = ['C', 'M', 'Y', 'R', 'G', 'B'][surf_count % 6])
pymevis.add_layer(layer)

# visgui.RefreshView()

lw update
Disposing of HistLimitsEditor
Disposing of HistLimitsEditor
Creating layers GUI
hl update
hl update
hl update
height:  360
NB best size: wx.Size(200, 360)


In [9]:
# pipeline.dataSources['surf0'].manifold

In [10]:
# np.histogram((mesh.vertices**2).sum(1))
# mesh.vertices[(mesh.vertices**2).sum(1)>5e6]

In [11]:
# %timeit np.zeros(1000,dtype=float)

In [12]:
# a = np.zeros(1000,dtype=float)

In [13]:
# %timeit a[:] = 0

In [14]:
# a = np.random.rand(3)

In [15]:
# %timeit np.linalg.norm(a)

In [16]:
# %timeit math.sqrt(a[0]*a[0]+a[1]*a[1]+a[2]*a[2])

In [17]:
# import math
# mesh.curvature_mean

In [18]:
mesh.curvature_mean

# array([-4.17393148e-02, -6.47531599e-02, -6.28658161e-02, -7.32509643e-02,
#        -4.44494225e-02, -4.02175561e-02, -9.65289250e-02, -2.99589038e-02,
#         7.46115446e-02, -2.54523233e-02, -4.36336733e-02, -9.75034200e-04,
#        -3.29364687e-02,  3.65853794e-02, -4.53770533e-02, -4.07672673e-02,
#        -7.05914348e-02, -1.27692251e-02, -4.19594571e-02, -2.23365426e-03,
#         9.56428982e-03, -6.48835897e-02, -3.39734033e-02, -3.65441740e-02,
#         2.12821690e-03, -4.23384756e-02, -6.61004111e-02, -4.17828038e-02,
#        -7.99856633e-02, -3.04907337e-02, -4.40911017e-02, -4.06354442e-02,
#        -5.27081415e-02,  1.55793410e-03, -1.42875966e-02, -2.12022103e-02,
#        -4.88264449e-02, -2.58695371e-02, -4.71302047e-02,  2.04286166e-03,
#        -3.28191817e-02, -5.62741514e-03,  9.68748890e-03, -4.27828878e-02,
#        -3.51782292e-02, -6.84810653e-02, -2.97071412e-02, -3.27480175e-02,
#        -6.18698895e-02,  3.99614405e-03, -4.60903421e-02, -3.29854265e-02,
#         9.67951864e-03,  6.07929230e-02, -3.83051764e-03,  1.59379151e-02,
#        -2.48886645e-02,  1.77249871e-02, -4.58422750e-02, -3.31686847e-02,
#        -2.35633571e-02, -4.34398204e-02, -1.67954825e-02, -3.63537520e-02,
#        -3.78030315e-02, -1.01542464e-02, -1.89266391e-02, -2.21120659e-02,
#        -3.42807546e-02, -2.57112272e-02, -7.62552917e-02, -1.89317502e-02,
#        -4.15192172e-02, -4.15229611e-02, -4.43957895e-02, -2.78975610e-02,
#        -1.00997742e-02, -6.64476827e-02, -2.45173015e-02, -5.40457200e-03,
#        -1.04349516e-02, -2.16272287e-02, -8.95028487e-02,  1.17024943e-01,
#        -2.48839967e-02, -3.17928344e-02, -1.84781626e-02, -5.69824129e-02,
#        -1.90435201e-02, -1.86022706e-02, -1.65337697e-02, -2.21876558e-02,
#        -2.03001648e-02, -3.35908905e-02, -3.77454571e-02, -2.33387649e-02,
#        -6.13679178e-04, -1.28951687e-02, -2.97874752e-02, -6.20161593e-02,
#         6.56416565e-02, -2.40163654e-02, -1.67674236e-02, -2.91693602e-02,
#         2.05748305e-02,  1.54502615e-02, -1.40088517e-02, -6.35759979e-02,
#        -6.78511858e-02, -2.07820162e-02, -1.51079558e-02, -2.25400105e-02,
#        -7.01756310e-03, -4.07542884e-02, -1.54313911e-02, -1.72125679e-02,
#        -4.81979325e-02, -1.69506483e-02, -1.66881606e-02, -2.49494463e-02,
#        -2.14403924e-02, -1.98856220e-02, -4.58582193e-02, -6.72279745e-02,
#        -4.62458767e-02, -9.95649397e-03,  4.15566266e-02, -4.03481051e-02,
#        -1.26126818e-02, -1.31162405e-02, -3.67801860e-02,  1.88357122e-02,
#        -3.37542407e-02, -1.25995763e-02, -9.11695883e-03, -2.06472166e-02,
#        -1.75201297e-02, -5.96642215e-03, -1.95242167e-02, -2.41531283e-02,
#         1.19527970e-02, -3.05645056e-02, -2.02659760e-02, -5.49855158e-02,
#        -7.28097837e-03, -3.25332768e-02, -9.43689793e-03, -3.19662280e-02,
#        -2.26963311e-03, -5.13175922e-03, -1.41660068e-02, -1.31830648e-02,
#        -1.75753273e-02,  3.52276266e-02, -8.95975754e-02, -8.10489990e-03,
#        -1.93999670e-02, -5.38160186e-03, -2.63635404e-02, -9.66210966e-04,
#        -2.13634558e-02, -3.72928241e-03,  1.61343778e-04, -1.43690612e-02,
#        -3.21473219e-02, -1.63269248e-02, -2.62577701e-02, -2.21767668e-02,
#        -3.70105654e-02, -8.14117957e-03, -2.05151550e-02, -8.55748821e-03,
#        -1.17373407e-01,  6.41156286e-02,  1.64988800e-04, -7.88473710e-03,
#        -1.46079790e-02, -2.94010527e-02, -7.82234669e-02, -3.54778990e-02,
#         1.31389243e-04, -2.19982769e-02, -2.60945726e-02,  1.76108512e-03,
#         1.38947368e-03, -1.25969830e-03, -4.03515771e-02,  1.02871296e-03,
#        -1.37279928e-02, -6.47364836e-03, -1.60273239e-02, -1.85495410e-02,
#        -4.18729633e-02, -4.46976945e-02, -2.31123436e-02,  6.60018399e-02,
#        -2.15431303e-02, -3.90199609e-02, -2.06800587e-02, -1.49850976e-02,
#        -4.37932322e-05,  1.41184474e-03, -6.59713894e-03, -1.39709357e-02,
#         2.88979523e-03, -1.31215276e-02, -5.18775638e-03, -8.91447254e-03,
#        -1.93076301e-02,  1.85997575e-03, -3.97649631e-02,  2.34514941e-03,
#        -5.12682423e-02,  2.88241170e-03, -5.85577101e-04, -1.02437548e-02,
#        -6.86257845e-04, -4.35047783e-02, -2.48701815e-02, -2.27445476e-02,
#        -1.37203950e-02,  3.03598726e-03, -7.40592778e-02,  4.10625674e-02,
#        -5.71897812e-03, -1.79752596e-02, -1.21197775e-02, -5.83618879e-04,
#        -3.90976593e-02,  3.41837341e-03, -1.67288035e-02,  1.65435555e-03,
#        -2.50071343e-02, -2.78572552e-02,  1.64001379e-02, -1.05691180e-02,
#         3.03304568e-03, -2.75173150e-02, -4.41341400e-02, -3.30932736e-02,
#        -3.31986025e-02,  7.87316822e-05,  7.98465102e-04, -5.71726263e-03,
#         3.03353230e-03, -4.52962704e-02, -2.66689865e-04, -1.09765418e-02,
#         4.46142489e-03, -2.50719525e-02,  1.69592025e-03,  3.72973830e-03,
#        -5.80661222e-02,  3.45806219e-03,  4.47452068e-03, -1.98222473e-02,
#        -1.20855477e-02, -1.96452141e-02, -4.18385379e-02, -2.70999111e-02,
#        -3.44511718e-02,  3.01338825e-03, -1.23326629e-02, -1.90351140e-02,
#         1.85478455e-03, -4.71801823e-03, -5.98804429e-02, -7.70682395e-02,
#         4.56642546e-03, -3.10385525e-02, -2.62000524e-02, -3.20563726e-02,
#         2.90358812e-03, -3.84801626e-02,  4.47842060e-03, -2.66598389e-02,
#         7.81450868e-02, -9.58853438e-02,  1.85833825e-03, -7.57360552e-03,
#        -1.37396366e-03,  4.89363447e-03,  1.18113676e-04, -7.57634733e-03,
#        -1.66994631e-02,  2.85069039e-03,  3.97847733e-03, -2.15965174e-02,
#        -5.11289239e-02,  2.64029833e-03, -2.18697190e-02, -8.08387622e-03,
#         3.53396311e-03, -1.73007883e-02,  3.66630312e-03, -3.42159718e-02,
#        -2.53536515e-02,  2.81584379e-03,  4.28627199e-03, -5.64247975e-03,
#         8.32872652e-03, -2.93004755e-02, -2.00890042e-02,  1.52642140e-03,
#        -5.85580878e-02, -3.44644561e-02, -2.61406898e-02, -1.53620914e-02,
#        -2.32072677e-02,  4.04385477e-03,  4.72844113e-03, -2.68657394e-02,
#        -3.61197032e-02, -6.12945994e-04, -3.74926776e-02,  9.68657027e-04,
#        -3.60943610e-03,  3.15198256e-03, -1.52402557e-02, -7.71673918e-02,
#        -2.16352213e-02, -9.96172708e-03, -2.01606825e-02, -1.77513361e-02,
#        -6.35852711e-03, -3.00635658e-02, -1.19601153e-02,  1.96109712e-03,
#         6.54418254e-05,  2.33605690e-03, -5.64329210e-04, -1.56088620e-02,
#         3.07171117e-03, -2.59873644e-02, -2.90539116e-02, -1.87285207e-02,
#        -3.26780528e-02, -2.04187147e-02, -1.68324150e-02, -2.06721742e-02,
#        -4.50056829e-02, -1.27770472e-05, -1.02914795e-02, -3.20285559e-03,
#        -7.71520566e-03, -3.52376029e-02, -7.29338359e-03, -6.60476368e-03,
#         2.04595737e-03, -2.49197297e-02,  1.52583362e-03, -3.17636179e-04,
#        -3.87257617e-03, -1.25264730e-02, -1.72580732e-03, -1.79025959e-02,
#        -1.19396802e-02,  2.66957134e-02, -8.65793228e-03, -1.14595592e-02,
#        -6.24227850e-03, -5.03723174e-02, -2.08134833e-03, -1.92697048e-02,
#        -1.74486954e-02, -9.11643147e-04, -3.63807529e-02, -2.18028715e-03,
#        -2.11718641e-02, -3.34230140e-02, -1.89954601e-02,  3.56059661e-03,
#        -2.19123960e-02, -8.18219036e-02, -1.94848515e-02, -8.04364495e-03,
#        -3.96688096e-03, -8.25828779e-03, -4.25908230e-02, -1.57636739e-02,
#        -7.32226390e-03, -4.86698076e-02, -1.61470957e-02, -1.47179905e-02,
#         1.23523362e-03, -7.03417882e-03, -2.58280747e-02, -5.12306392e-03,
#        -4.09120992e-02, -7.95429200e-03, -1.25317480e-02, -3.17243710e-02,
#        -8.35311189e-02, -6.93123490e-02,  1.60713285e-01, -1.39362626e-02,
#        -1.00669134e-02, -2.61594765e-02, -2.01035999e-02, -1.67774949e-02,
#        -2.38017961e-02, -1.57375336e-01, -1.82958722e-01, -2.46518627e-02,
#        -1.98373254e-02, -2.97736432e-02, -2.40573287e-02, -9.88375861e-03,
#        -2.14881077e-02, -1.33556733e-02, -1.56815536e-02,  1.18914954e-02,
#        -9.93138365e-03, -3.74695212e-02, -6.66424930e-02, -3.68143469e-02,
#        -4.28410321e-02, -4.56344672e-02, -3.18404958e-02,  4.66303974e-02,
#         8.26482549e-02, -2.22984441e-02, -1.79788694e-02, -2.89919656e-02,
#        -1.91097371e-02, -2.43791305e-02, -2.27627177e-02, -1.94384176e-02,
#        -4.59973002e-03, -6.26882240e-02, -2.10393332e-02, -1.84654482e-02,
#         2.73990240e-02, -2.78297625e-02, -3.77888605e-02, -1.04594957e-02,
#        -1.90752335e-02,  7.52030760e-02, -2.36891024e-02, -1.68895498e-02,
#        -1.57192294e-02, -1.48285693e-03, -6.96736015e-03, -1.22151114e-02,
#         7.19016092e-03, -9.88590047e-02, -4.22107540e-02, -3.02398168e-02,
#        -7.45662600e-02, -1.70437507e-02, -2.75307521e-02, -1.04919441e-01,
#        -6.95630014e-02, -7.50906765e-02, -3.98133136e-02, -1.21011157e-02,
#         1.27300113e-01, -1.29404575e-01, -1.56703498e-02, -2.87699923e-02,
#        -1.22306338e-02, -2.61298418e-01, -8.99995863e-02, -1.79302674e-02,
#        -2.95647886e-04,  2.09628493e-01,  6.48103058e-02, -2.51266137e-02,
#        -1.70044482e-01, -1.38520412e-02, -8.38196427e-02, -1.30427089e-02,
#        -1.80121213e-02, -3.46561819e-02, -3.14367749e-02, -1.28144801e-01,
#        -1.68929100e-02, -2.22962610e-02, -3.24110761e-02,  6.15888759e-02,
#        -1.36700869e-02, -2.08517537e-02, -1.58601850e-02, -3.22164372e-02,
#         4.14570794e-04, -2.73230840e-02, -2.48234607e-02, -3.39941978e-02,
#        -4.27926444e-02,  1.85517557e-02, -4.27531302e-02, -6.14377446e-02,
#        -6.76450551e-01,  4.00707708e-04, -8.58421437e-03, -3.96438874e-02,
#        -9.97793302e-03, -3.08265127e-02, -3.30279358e-02, -4.58002910e-02,
#        -2.96460763e-02, -7.78832659e-03, -2.13446394e-02, -1.78585202e-02,
#         7.57997409e-02,  9.10350122e-04, -5.45607321e-02, -1.08721979e-01,
#        -1.95199288e-02, -1.13106146e-03, -2.80546173e-02, -2.99392603e-02,
#        -1.53839692e-01, -1.89011004e-02, -1.98956244e-02, -3.79166529e-02,
#        -5.49232066e-02, -5.49355894e-02, -5.36268428e-02,  2.28421658e-01,
#         4.22268827e-03, -4.45857011e-02, -1.76307172e-01,  1.04551911e-02,
#         1.11595660e-01, -4.57154512e-02, -7.79497027e-02, -1.55391380e-01,
#        -4.92263511e-02], dtype=float32)

array([-0.02428699, -0.02683684, -0.03520463, -0.03526436, -0.02588729,
       -0.01925983, -0.02496032, -0.03601997, -0.03186244, -0.02513247,
       -0.01710546, -0.02181269, -0.03572722, -0.03095525, -0.02884807,
       -0.02043651, -0.02260816, -0.0107248 , -0.01783027, -0.02440133,
       -0.01989751, -0.0300505 , -0.02325139, -0.03114404, -0.03416455,
       -0.02380164, -0.02358823, -0.01761594, -0.02641878, -0.01438287,
       -0.0193562 , -0.02085626, -0.0029468 , -0.01964906, -0.00958929,
       -0.02563001, -0.03561622, -0.00939163, -0.031532  , -0.02300384,
       -0.02635964, -0.02772332, -0.02310884, -0.02327645, -0.0072066 ,
       -0.02903603, -0.01831257, -0.02788141, -0.04116877, -0.02206988,
       -0.01740585, -0.02495094, -0.01955125, -0.01970816, -0.01835   ,
       -0.0247904 , -0.02731424, -0.01983626, -0.01559758, -0.02533107,
       -0.0352015 , -0.0280713 , -0.02011003, -0.02124435, -0.0150802 ,
       -0.01749244, -0.02111065, -0.0214844 , -0.02949768, -0.02

In [19]:
mesh._E

# array([3.69682997e-01, 7.27405965e-01, 5.06314933e-01, 8.97472680e-01,
#        4.26163256e-01, 2.94352949e-01, 7.62914002e-01, 1.73212513e-01,
#        1.18350375e+00, 1.64869383e-01, 4.19751137e-01, 2.63720867e-04,
#        2.05418035e-01, 2.71241367e-01, 4.63015854e-01, 2.98604935e-01,
#        1.43914378e+00, 5.97544834e-02, 3.29741001e-01, 7.06293853e-04,
#        1.42374961e-02, 1.21098804e+00, 1.65154859e-01, 3.63897085e-01,
#        7.99446658e-04, 5.28342128e-01, 8.46490681e-01, 2.33832851e-01,
#        1.41649616e+00, 2.50167638e-01, 4.27326173e-01, 3.21136117e-01,
#        1.39245689e-01, 4.82893491e-04, 4.98549454e-02, 1.57195330e-01,
#        3.68943125e-01, 1.62405625e-01, 5.58447719e-01, 6.52595074e-04,
#        1.56077102e-01, 3.50140990e-03, 2.19072234e-02, 3.15125763e-01,
#        2.51303375e-01, 1.60214555e+00, 1.75820291e-01, 2.82086134e-01,
#        7.49138057e-01, 3.30463424e-03, 4.80607599e-01, 3.49312186e-01,
#        1.59917958e-02, 5.37026644e-01, 6.59460947e-03, 7.69030824e-02,
#        8.77946764e-02, 1.46080390e-01, 2.82161087e-01, 2.17428565e-01,
#        9.41009000e-02, 3.17319185e-01, 3.16981487e-02, 1.65952191e-01,
#        3.05103481e-01, 3.68916094e-02, 1.18386745e-01, 1.30224407e-01,
#        2.73441136e-01, 1.52113348e-01, 1.03600240e+00, 7.78151602e-02,
#        5.40736675e-01, 3.12741280e-01, 5.17471969e-01, 2.86534339e-01,
#        2.51386408e-02, 9.19420540e-01, 1.61926255e-01, 1.03018358e-02,
#        2.75991689e-02, 1.41699985e-01, 7.80647457e-01, 2.86214352e+00,
#        1.48455262e-01, 2.39071831e-01, 7.73138180e-02, 7.25610435e-01,
#        7.22634792e-02, 8.11595619e-02, 3.36767994e-02, 8.79048780e-02,
#        1.50458544e-01, 3.13291669e-01, 2.99683630e-01, 9.10670087e-02,
#        1.05450439e-04, 4.83932570e-02, 3.18588823e-01, 7.99553156e-01,
#        9.14955497e-01, 2.08222732e-01, 8.47246572e-02, 1.91898152e-01,
#        1.15944728e-01, 4.10218649e-02, 5.61253950e-02, 1.05814195e+00,
#        1.32288325e+00, 1.16868496e-01, 8.42376351e-02, 1.06145889e-01,
#        9.58615821e-03, 4.38825369e-01, 4.23438884e-02, 8.53572413e-02,
#        4.92707133e-01, 6.48609996e-02, 1.30784541e-01, 1.83082879e-01,
#        1.23782761e-01, 7.32301921e-02, 1.98936120e-01, 5.40372491e-01,
#        5.05901337e-01, 2.44064648e-02, 1.92491397e-01, 3.51677358e-01,
#        3.87250818e-02, 5.21931499e-02, 3.77299756e-01, 8.77610445e-02,
#        1.95649788e-01, 5.08912988e-02, 1.62839703e-02, 1.18095666e-01,
#        8.48328024e-02, 1.04581099e-02, 7.96342939e-02, 2.05044568e-01,
#        2.29185820e-02, 1.84219718e-01, 1.69426993e-01, 4.69145149e-01,
#        1.72494892e-02, 1.99943259e-01, 3.71639431e-02, 3.82141978e-01,
#        1.66014826e-03, 6.16025086e-03, 2.56973207e-02, 1.49452565e-02,
#        1.10968925e-01, 4.11132157e-01, 1.66390455e+00, 9.90479626e-03,
#        5.20778857e-02, 1.24464426e-02, 2.26144850e-01, 2.52221274e-04,
#        1.15595974e-01, 2.86404137e-03, 6.90212710e-06, 7.74937496e-02,
#        1.78974286e-01, 6.05520830e-02, 2.14833558e-01, 7.50353858e-02,
#        1.30739346e-01, 1.39206378e-02, 1.91703469e-01, 1.55638745e-02,
#        5.90185213e+00, 1.08601201e+00, 4.63476636e-06, 1.83795262e-02,
#        7.59348646e-02, 1.70432761e-01, 9.02098536e-01, 2.23673314e-01,
#        4.36879100e-06, 1.55954957e-01, 1.01375215e-01, 6.67056825e-04,
#        6.18985621e-04, 2.55868945e-04, 3.59476745e-01, 3.67150700e-04,
#        3.00738290e-02, 1.00117726e-02, 2.99086235e-02, 1.09744996e-01,
#        3.40976417e-01, 4.50526029e-01, 8.42154026e-02, 9.52270031e-01,
#        9.32238027e-02, 6.17210746e-01, 1.32757708e-01, 3.93489338e-02,
#        6.75293904e-07, 3.50184389e-04, 9.66561586e-03, 5.57345226e-02,
#        2.44423794e-03, 2.57041287e-02, 8.64316151e-03, 2.66339127e-02,
#        5.83472028e-02, 1.20814785e-03, 3.41924191e-01, 1.64640578e-03,
#        5.95040262e-01, 3.55655071e-03, 6.97745854e-05, 1.30367624e-02,
#        8.17921391e-05, 3.41332644e-01, 3.32048297e-01, 1.13362506e-01,
#        7.81573355e-02, 2.50051357e-03, 1.18860102e+00, 3.08291644e-01,
#        7.69055868e-03, 7.19472840e-02, 3.55195925e-02, 8.67407507e-05,
#        3.81831467e-01, 3.82430223e-03, 9.70377326e-02, 5.42883412e-04,
#        1.39224544e-01, 1.69776604e-01, 8.09916034e-02, 2.70150974e-02,
#        3.85431061e-03, 2.65640169e-01, 3.43803376e-01, 2.59320110e-01,
#        1.84990436e-01, 1.40873260e-06, 1.62492652e-04, 7.71106547e-03,
#        1.81035546e-03, 3.56911361e-01, 1.40247557e-05, 4.43917066e-02,
#        5.37488889e-03, 9.90400761e-02, 1.33324275e-03, 4.93562594e-03,
#        8.58829141e-01, 3.54707590e-03, 7.99028855e-03, 3.50407213e-02,
#        2.47834790e-02, 1.03243351e-01, 4.80182618e-01, 2.06385151e-01,
#        2.60418355e-01, 2.49653729e-03, 5.57365008e-02, 1.29144147e-01,
#        5.08303056e-04, 8.30600597e-03, 9.93992686e-01, 1.22557807e+00,
#        3.05493921e-03, 1.92470610e-01, 1.69275671e-01, 2.64628232e-01,
#        2.29966291e-03, 2.71362633e-01, 6.27642125e-03, 1.01221986e-01,
#        5.46512783e-01, 2.12345266e+00, 1.02513656e-03, 2.24251058e-02,
#        6.51083537e-04, 8.04324076e-03, 4.78785432e-06, 1.43505773e-02,
#        6.82906732e-02, 2.25386512e-03, 5.82393212e-03, 1.57853305e-01,
#        5.91058135e-01, 2.07100390e-03, 1.35089651e-01, 1.24766408e-02,
#        5.46715129e-03, 8.01499709e-02, 3.42883426e-03, 2.95346022e-01,
#        1.16293818e-01, 2.46290956e-03, 5.87539561e-03, 9.55647882e-03,
#        8.37643538e-03, 1.73541799e-01, 1.06269702e-01, 6.28658046e-04,
#        3.79177064e-01, 2.57005125e-01, 1.29783750e-01, 7.06749037e-02,
#        1.44039139e-01, 6.50321972e-03, 5.56851225e-03, 2.21148908e-01,
#        2.91944504e-01, 1.16815361e-04, 3.22206885e-01, 2.70162855e-04,
#        3.52388271e-03, 2.86639039e-03, 4.53332961e-02, 1.41626084e+00,
#        9.19625834e-02, 4.83973436e-02, 1.02590352e-01, 7.71219581e-02,
#        8.66007712e-03, 2.00880945e-01, 4.07236926e-02, 1.27984094e-03,
#        8.09017877e-07, 1.74378895e-03, 1.48382416e-04, 5.95005490e-02,
#        3.79940984e-03, 2.76049316e-01, 2.76620179e-01, 8.90936926e-02,
#        2.48087138e-01, 8.97577628e-02, 6.28690720e-02, 9.25786942e-02,
#        3.79147142e-01, 4.09031777e-08, 3.18766050e-02, 1.81270903e-03,
#        1.68890171e-02, 3.45682800e-01, 2.27082334e-02, 9.26394109e-03,
#        1.89549802e-03, 1.14606887e-01, 7.97919056e-04, 1.54722238e-05,
#        4.96097654e-03, 5.28343469e-02, 3.32045747e-04, 8.14341158e-02,
#        6.63791895e-02, 1.87464505e-01, 2.65461858e-02, 3.12996358e-02,
#        4.81765997e-03, 5.39436042e-01, 1.38287141e-03, 1.04141541e-01,
#        8.37886035e-02, 2.26004369e-04, 2.34665111e-01, 1.18178246e-03,
#        1.10173315e-01, 3.53527427e-01, 1.84905037e-01, 1.86651188e-03,
#        9.98863652e-02, 8.73050094e-01, 1.41749799e-01, 1.08711831e-02,
#        5.21119591e-03, 1.88157484e-02, 5.81874967e-01, 7.67582953e-02,
#        1.01607349e-02, 4.65297103e-01, 6.06950819e-02, 5.58386259e-02,
#        3.45562206e-04, 2.23506615e-02, 6.99818656e-02, 7.58144539e-03,
#        1.96702316e-01, 1.48858577e-02, 4.24468555e-02, 2.70692796e-01,
#        1.33459187e+00, 5.08094907e-01, 1.83932078e+00, 6.14187233e-02,
#        2.60402393e-02, 2.30329663e-01, 1.15140945e-01, 1.08000249e-01,
#        1.65879428e-01, 4.16927099e+00, 4.93245077e+00, 1.58463106e-01,
#        1.26100510e-01, 2.11289719e-01, 8.94797072e-02, 2.58040708e-02,
#        1.34333953e-01, 5.53649850e-02, 4.86916192e-02, 3.02025694e-02,
#        2.18076464e-02, 3.80151510e-01, 9.08602655e-01, 3.27463925e-01,
#        4.90380526e-01, 3.90826285e-01, 4.30023432e-01, 1.56382605e-01,
#        7.10723460e-01, 6.90325424e-02, 9.63067710e-02, 1.78206533e-01,
#        9.99680236e-02, 1.80754438e-01, 1.99447274e-01, 5.57062179e-02,
#        4.35096398e-03, 5.61352491e-01, 1.27106667e-01, 1.07005306e-01,
#        6.89562485e-02, 2.12698191e-01, 5.24374783e-01, 3.51775549e-02,
#        1.24321692e-01, 1.40048146e+00, 2.18169495e-01, 7.34059215e-02,
#        7.49030784e-02, 3.99885088e-04, 1.26200914e-02, 3.19025517e-02,
#        2.20975690e-02, 8.47572148e-01, 2.78665185e-01, 3.83254737e-01,
#        8.96310747e-01, 1.02417916e-01, 1.72578976e-01, 1.22296548e+00,
#        8.90873730e-01, 6.19743288e-01, 4.77590889e-01, 3.77534255e-02,
#        1.91709995e+00, 2.12790895e+00, 5.08749150e-02, 2.82468826e-01,
#        3.38460952e-02, 8.95871735e+00, 2.03491759e+00, 1.14363648e-01,
#        2.55390187e-05, 4.32815266e+00, 5.02354503e-01, 1.64375857e-01,
#        3.16911554e+00, 4.81380522e-02, 1.04062676e+00, 5.31615838e-02,
#        8.56282488e-02, 3.12056631e-01, 2.16277018e-01, 2.09071112e+00,
#        7.47078210e-02, 1.73131868e-01, 3.58639657e-01, 7.55348504e-01,
#        2.08612885e-02, 5.48971146e-02, 7.81460926e-02, 1.88459486e-01,
#        4.86682802e-05, 1.69235840e-01, 9.96863469e-02, 3.81891102e-01,
#        4.76392299e-01, 8.40146020e-02, 2.28764430e-01, 7.96555579e-01,
#        7.99495468e+01, 4.94785418e-05, 3.33864093e-02, 4.39785600e-01,
#        3.17296386e-02, 2.88339823e-01, 3.45691085e-01, 2.40297377e-01,
#        9.22422633e-02, 1.02603277e-02, 8.94212872e-02, 1.06680900e-01,
#        7.78991997e-01, 1.57840564e-04, 3.36471438e-01, 1.38687611e+00,
#        1.86477438e-01, 1.66615529e-04, 3.09009373e-01, 1.83696970e-01,
#        4.83983231e+00, 5.47438264e-02, 1.09053150e-01, 4.26671892e-01,
#        4.16210055e-01, 3.33404124e-01, 3.87260109e-01, 3.74135303e+00,
#        2.21606554e-03, 2.58567899e-01, 7.42366409e+00, 1.18872160e-02,
#        6.51783943e-01, 3.40815097e-01, 9.42807138e-01, 3.07629728e+00,
#        3.25507104e-01], dtype=float32)


array([2.11844757e-01, 2.40198106e-01, 3.19626093e-01, 4.17075068e-01,
       2.46623173e-01, 1.20239317e-01, 1.14637233e-01, 4.29192245e-01,
       3.56957167e-01, 2.29203776e-01, 1.04349464e-01, 1.81151569e-01,
       3.98130208e-01, 2.54946232e-01, 3.37461829e-01, 1.41302496e-01,
       2.45739833e-01, 5.14777005e-02, 8.57661143e-02, 1.31548330e-01,
       1.00605771e-01, 3.08747321e-01, 1.27968907e-01, 3.62230748e-01,
       3.35921764e-01, 2.29208544e-01, 1.33878291e-01, 7.86462128e-02,
       2.58702904e-01, 6.29288033e-02, 1.40812173e-01, 1.12942219e-01,
       6.23609754e-04, 1.14936337e-01, 2.44266633e-02, 2.75681525e-01,
       2.91851372e-01, 2.50656456e-02, 3.79334241e-01, 1.43675789e-01,
       1.45927966e-01, 1.79455012e-01, 1.44920379e-01, 1.59630924e-01,
       1.40660116e-02, 3.92872155e-01, 9.11607444e-02, 2.50618219e-01,
       5.91276884e-01, 1.31263480e-01, 9.42734703e-02, 2.49100611e-01,
       8.34460780e-02, 7.19749853e-02, 1.95434555e-01, 2.34105453e-01,
      

ERROR:traitsui.wx.toolkit:Wx control <traitsui.wx.helper.TraitsUIPanel object at 0x7f92aefa04b0> not destroyed cleanly
Traceback (most recent call last):
  File "/Users/zachcm/opt/miniconda3/envs/pyme/lib/python3.7/site-packages/traitsui/wx/toolkit.py", line 436, in _destroy_control
    control.Destroy()
  File "/Users/zachcm/opt/miniconda3/envs/pyme/lib/python3.7/site-packages/traitsui/wx/helper.py", line 326, in Destroy
    self.Unbind(wx.EVT_CHILD_FOCUS)
  File "/Users/zachcm/opt/miniconda3/envs/pyme/lib/python3.7/site-packages/wx/core.py", line 1416, in _EvtHandler_Unbind
    return event.Unbind(self, id, id2, handler)
  File "/Users/zachcm/opt/miniconda3/envs/pyme/lib/python3.7/site-packages/wx/core.py", line 1485, in Unbind
    success += int(target.Disconnect(id1, id2, et, handler))
RuntimeError: wrapped C/C++ object of type TraitsUIPanel has been deleted
ERROR:traitsui.wx.toolkit:Wx control <traitsui.wx.helper.TraitsUIPanel object at 0x7f92ae1a22d0> not destroyed cleanly
Traceb

Ev Idle
('points', 't')
refreshed


ERROR:traits:Exception occurred in traits notification handler for object: <PYME.LMVis.layers.pointcloud.PointCloudRenderLayer object at 0x7f92ae4c7d10>, trait: visible, old value: True, new value: False
Traceback (most recent call last):
  File "/Users/zachcm/opt/miniconda3/envs/pyme/lib/python3.7/site-packages/traits/trait_notifiers.py", line 522, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/Users/zachcm/opt/miniconda3/envs/pyme/lib/python3.7/site-packages/traits/trait_notifiers.py", line 484, in dispatch
    handler(*args)
  File "/Users/zachcm/Code/python-microscopy/PYME/LMVis/layers/pointcloud.py", line 120, in <lambda>
    self.on_trait_change(lambda: self.on_update.send(self), 'visible')
  File "/Users/zachcm/Code/python-microscopy/PYME/contrib/dispatch/dispatcher.py", line 174, in send
    for receiver in self._live_receivers(sender)
  File "/Users/zachcm/Code/python-microscopy/PYME/contrib/dispatch/dispatcher.py", line 174, in <listcomp>
    for receive

hl update


ERROR:traits:Exception occurred in traits notification handler for object: <PYME.LMVis.layers.mesh.TriangleRenderLayer object at 0x7f92ae9f3cb0>, trait: visible, old value: True, new value: False
Traceback (most recent call last):
  File "/Users/zachcm/opt/miniconda3/envs/pyme/lib/python3.7/site-packages/traits/trait_notifiers.py", line 522, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/Users/zachcm/opt/miniconda3/envs/pyme/lib/python3.7/site-packages/traits/trait_notifiers.py", line 484, in dispatch
    handler(*args)
  File "/Users/zachcm/Code/python-microscopy/PYME/ui/layerFoldPanel.py", line 98, in _refresh
    self.Refresh()
RuntimeError: wrapped C/C++ object of type LayerCaptionBar has been deleted


lw update
hl update
lw update
lw update
lw update
hl update
lw update
[-0.0006570468540303409, 0.0022444212809205055]
lw update
[-0.0004029026604257524, 0.0016146431444212794]
[-0.0004029026604257524, 0.0016146431444212794]
lw update
hl update
lw update
[-0.0492737740278244, 0.026293771341443062]
lw update
[-0.0424712710082531, 0.01757657714188099]
